 Python for Data Analysis and Data Science - Complete Notes

## Day 1 & 2: Introduction to Python

### 1. Need for Programming Language in Data Analysis and Data Science

"""
Why do we need programming in DA and DS?

1. Automation: Process large datasets automatically instead of manually
2. Reproducibility: Write code once, run multiple times with different data
3. Efficiency: Handle millions of rows of data in seconds
4. Complex Analysis: Perform statistical analysis, machine learning, and visualization
5. Scalability: Analyze small to extremely large datasets with same code

Real-world example:

- Manual Excel work: Analyzing 1000 rows might take hours
- Python: Can analyze millions of rows in minutes
"""

### 2. What is Python and Why Python?

"""
What is Python?
- Python is a high-level, interpreted programming language
- Created by Guido van Rossum in 1991
- Known for simple, readable syntax

Why Python for Data Analysis and Data Science?

1. Easy to Learn: Simple syntax, reads like English
2. Rich Libraries: NumPy, Pandas, Matplotlib, Scikit-learn
3. Large Community: Millions of developers, abundant resources
4. Versatile: Web development, automation, AI, data analysis
5. Industry Standard: Used by Google, Netflix, NASA, Instagram
6. Free and Open Source: No cost, anyone can contribute
"""

### 3. Libraries for Data Analysis and Data Science

"""
Essential Python Libraries:

1. NumPy: Numerical computing, arrays, mathematical operations
2. Pandas: Data manipulation, DataFrames, data cleaning
3. Matplotlib: Data visualization, creating plots and charts
4. Seaborn: Statistical data visualization, beautiful plots
5. Scikit-learn: Machine learning algorithms
6. TensorFlow/PyTorch: Deep learning and neural networks
7. SciPy: Scientific computing, statistics
8. Statsmodels: Statistical modeling and hypothesis testing
"""

### 4. IDEs for Python

"""
Popular IDEs and Environments:

1. Jupyter Notebook: Interactive notebooks, great for learning
2. Google Colab: Cloud-based Jupyter notebooks, free GPU
3. PyCharm: Professional IDE with many features
4. VS Code: Lightweight, extensible code editor
5. Spyder: IDE designed for data science
6. IDLE: Built-in Python IDE, simple for beginners
"""


In [ ]:
### 5. Running Simple Commands

# print() function - displays output
print("Hello, Students!")
print("Welcome to Python Programming")

Hello, Students!
Welcome to Python Programming


In [ ]:
# Multiple items in print
print("Python", "is", "awesome")

Python is awesome


In [ ]:
# Print numbers
print(42)
print(3.14)

42
3.14


In [ ]:
# type() function - shows data type
print(type(10))
print(type(3.14))
print(type("Hello"))
print(type(True))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [ ]:
# Example: Checking types
name = "Alice"
age = 25
print("Name:", name, "Type:", type(name))
print("Age:", age, "Type:", type(age))

Name: Alice Type: <class 'str'>
Age: 25 Type: <class 'int'>


"""
PRACTICE EXERCISE 1:
1. Print your name and age
2. Use type() to check the data type of your name
3. Use type() to check the data type of your age
4. Print a message: "I am learning Python for Data Science"
"""

## Day 3: Variables and Data Types

### 1. Creating Simple Variables

"""
What is a Variable?
- A variable is a container that stores data
- Think of it as a labeled box where you keep information
"""

In [ ]:
# Creating variables
student_name = "Rahul"
student_age = 20
student_marks = 85.5
is_passed = True

In [ ]:
print(student_name)
print(student_age)
print(student_marks)
print(is_passed)

Rahul
20
85.5
True


In [ ]:
# Multiple variables at once
x, y, z = 10, 20, 30
print(x, y, z)

10 20 30


In [ ]:
# Same value to multiple variables
a = b = c = 100
print(a, b, c)

100 100 100


### 2. Rules for Naming Variables

"""
Variable Naming Rules:

✓ CORRECT:
- Must start with letter or underscore: student_name, _temp
- Can contain letters, numbers, underscore: student1, data_2024
- Case sensitive: Name and name are different
- Use descriptive names: total_marks (good) vs tm (bad)

✗ WRONG:
- Cannot start with number: 1student
- Cannot use special characters: student-name, student@email
- Cannot use Python keywords: print, for, if, class
- Avoid spaces: student name (wrong), student_name (correct)

Best Practices:
- Use lowercase with underscores: student_marks
- Use meaningful names: total_score instead of ts
- Constants in UPPERCASE: PI = 3.14159
"""


In [ ]:
# Examples
student_name = "Priya"
_private_var = 42
student1_marks = 95

# 1student = "John"
# student-name = "Mike"

my_variable = "Data Science"
CONSTANT_VALUE = 3.14

"""
PRACTICE EXERCISE 2:
1. Create variables for: your name, city, favorite number, and whether you like programming
2. Print all variables
3. Try creating a variable with a wrong name (with number at start) and see the error
"""

### 3. Numeric Data Types

In [ ]:
# Integer (int) - Whole numbers
age = 25
year = 2024
quantity = -10
print("Integer examples:", age, year, quantity)
print("Type:", type(age))

Integer examples: 25 2024 -10
Type: <class 'int'>


In [ ]:
# Float - Decimal numbers
price = 99.99
temperature = 36.6
pi = 3.14159
print("Float examples:", price, temperature, pi)
print("Type:", type(price))

Float examples: 99.99 36.6 3.14159
Type: <class 'float'>


In [ ]:
# Boolean - True or False
is_student = True
has_passed = False
is_adult = True
print("Boolean examples:", is_student, has_passed)
print("Type:", type(is_student))

Boolean examples: True False
Type: <class 'bool'>


In [ ]:
# Complex - Complex numbers (rare in basic DA)
complex_num = 3 + 4j
print("Complex example:", complex_num)
print("Type:", type(complex_num))

Complex example: (3+4j)
Type: <class 'complex'>


In [ ]:
# Real-world example
student_name = "Amit"
student_marks = 87.5
is_passed = True
total_students = 50

In [ ]:
print("Student:", student_name)
print("Marks:", student_marks)
print("Passed:", is_passed)
print("Total Students:", total_students)

Student: Amit
Marks: 87.5
Passed: True
Total Students: 50


"""
PRACTICE EXERCISE 3:
1. Create variables for: temperature (float), number of students (int), is_raining (boolean)
2. Print each variable with its type
3. Create a variable for your height in feet (decimal number)
"""

### 4. Sequence Types: Strings, Lists, Tuples

## STRINGS - Text data in quotes

In [ ]:
# Creating strings
single_quote = 'Hello'
double_quote = "World"
multi_line = """This is
a multi-line
string"""

In [ ]:
name = "Python"
message = "Data Science is amazing!"
print(name)
print(message)

Python
Data Science is amazing!


In [ ]:
# String operations
first_name = "Ravi"
last_name = "Kumar"
full_name = first_name + " " + last_name  # Concatenation
print("Full Name:", full_name)

Full Name: Ravi Kumar


In [ ]:
# Repeating strings
laugh = "Ha" * 3
print(laugh)

HaHaHa


In [ ]:
# Creating lists
fruits = ["apple", "banana", "orange", "mango"]
numbers = [1, 2, 3, 4, 5]
mixed = ["Python", 100, 3.14, True]
empty_list = []

In [ ]:
print("Fruits:", fruits)
print("Numbers:", numbers)
print("Mixed:", mixed)
print("Type:", type(fruits))

Fruits: ['apple', 'banana', 'orange', 'mango']
Numbers: [1, 2, 3, 4, 5]
Mixed: ['Python', 100, 3.14, True]
Type: <class 'list'>


In [ ]:
# Accessing list elements (indexing starts at 0)
print("First fruit:", fruits[0])
print("Second fruit:", fruits[1])
print("Last fruit:", fruits[-1])

First fruit: apple
Second fruit: banana
Last fruit: mango


In [ ]:
# List can be modified
fruits[1] = "grapes"
print("Modified fruits:", fruits)

Modified fruits: ['apple', 'grapes', 'orange', 'mango']


In [ ]:
# Real-world example
student_marks = [85, 90, 78, 92, 88]
print("All marks:", student_marks)
print("First student marks:", student_marks[0])
print("Last student marks:", student_marks[-1])

All marks: [85, 90, 78, 92, 88]
First student marks: 85
Last student marks: 88


## TUPLES - Ordered, immutable collection

In [ ]:
# Creating tuples
coordinates = (10, 20)
rgb_color = (255, 0, 128)
student_info = ("Rahul", 20, "Computer Science")
single_item = (42,) # Note the comma for single item

In [ ]:
print("Coordinates:", coordinates)
print("Color:", rgb_color)
print("Student:", student_info)
print("Type:", type(coordinates))

Coordinates: (10, 20)
Color: (255, 0, 128)
Student: ('Rahul', 20, 'Computer Science')
Type: <class 'tuple'>


In [ ]:
# Accessing tuple elements
print("X coordinate:", coordinates[0])
print("Y coordinate:", coordinates[1])
print("Student name:", student_info[0])

X coordinate: 10
Y coordinate: 20
Student name: Rahul


In [ ]:
# Tuples cannot be modified
# coordinates[0] = 30

In [ ]:
# When to use List vs Tuple?
# List: When data might change (shopping cart items)
# Tuple: When data should not change (latitude-longitude, RGB colors)

"""
PRACTICE EXERCISE 4:
1. Create a list of your 5 favorite movies
2. Print the first and last movie from the list
3. Change the second movie to a different one
4. Create a tuple with your birth date (day, month, year)
5. Print the year from the tuple
"""

## Day 4: Type Casting and String Operations

### 1. Type Casting - Converting Data Types


-Type Casting: Converting one data type to another

* Why needed? To perform operations that require specific types


In [ ]:
# Integer to Float
num_int = 10
num_float = float(num_int)
print("Integer:", num_int, type(num_int))
print("To Float:", num_float, type(num_float))

Integer: 10 <class 'int'>
To Float: 10.0 <class 'float'>


In [ ]:
# Float to Integer (decimal part is removed, not rounded)
price = 99.99
price_int = int(price)
print("Float:", price, type(price))
print("To Integer:", price_int, type(price_int))

Float: 99.99 <class 'float'>
To Integer: 99 <class 'int'>


In [ ]:
# String to Integer
age_str = "25"
age_int = int(age_str)
print("String:", age_str, type(age_str))
print("To Integer:", age_int, type(age_int))

String: 25 <class 'str'>
To Integer: 25 <class 'int'>


In [ ]:
# String to Float
price_str = "49.99"
price_float = float(price_str)
print("String:", price_str, type(price_str))
print("To Float:", price_float, type(price_float))

String: 49.99 <class 'str'>
To Float: 49.99 <class 'float'>


In [ ]:
# Integer/Float to String
marks = 95
marks_str = str(marks)
print("Integer:", marks, type(marks))
print("To String:", marks_str, type(marks_str))

Integer: 95 <class 'int'>
To String: 95 <class 'str'>


In [ ]:
# Boolean conversions
print("To Boolean:")
print("int to bool:", bool(0), bool(1), bool(100))  # 0 is False, non-zero is True
print("str to bool:", bool(""), bool("Hello"))

To Boolean:
int to bool: False True True
str to bool: False True


In [ ]:
# Real-world example: User input
user_age = "22"  # User inputs are always strings
user_age_int = int(user_age)
next_year_age = user_age_int + 1
print("Current age:", user_age_int)
print("Next year:", next_year_age)

Current age: 22
Next year: 23


In [ ]:
# Calculation example
num1_str = "10"
num2_str = "20"

In [ ]:
# sum_wrong = num1_str + num2_str  # This gives "1020" (concatenation)
sum_correct = int(num1_str) + int(num2_str)
print("Correct sum:", sum_correct)

Correct sum: 30


PRACTICE EXERCISE 5:
1. Create a string variable with value "100" and convert it to integer
2. Create a float variable 78.9 and convert it to integer
3. Create an integer 50 and convert it to string, then print its type
4. Take two string numbers "15" and "25", convert to integers and find their sum


### 2. Strings: String Methods, Indexing, Slicing

## String Indexing

In [ ]:
text = "Python"
# Index:  0 1 2 3 4 5
#        -6-5-4-3-2-1

print("First character:", text[0])
print("Third character:", text[2])
print("Last character:", text[-1])
print("Second last:", text[-2])

First character: P
Third character: t
Last character: n
Second last: o


In [ ]:
## String Slicing - Extracting parts of string
message = "Data Science"

## String Slicing - Extracting parts of string

In [ ]:
message = "Data Science"
# Syntax: string[start:end]  (end is not included)

print("First 4 characters:", message[0:4])
print("From index 5 to end:", message[5:])
print("From start to index 4:", message[:4])
print("Last 7 characters:", message[-7:])
print("Every 2nd character:", message[::2])
print("Reverse string:", message[::-1])

First 4 characters: Data
From index 5 to end: Science
From start to index 4: Data
Last 7 characters: Science
Every 2nd character: Dt cec
Reverse string: ecneicS ataD


In [ ]:
# Practical examples
email = "student@gmail.com"
username = email[0:7]  # Extract username
print("Username:", username)

phone = "9876543210"
area_code = phone[0:3]
print("Area code:", area_code)

Username: student
Area code: 987


## String Methods

In [ ]:
text = "  Hello World  "
# Case conversion
print("Upper:", text.upper())
print("Lower:", text.lower())
print("Title:", text.title())
print("Capitalize:", text.capitalize())
print("Swap case:", text.swapcase())

Upper:   HELLO WORLD  
Lower:   hello world  
Title:   Hello World  
Capitalize:   hello world  
Swap case:   hELLO wORLD  


In [ ]:
# Searching
sentence = "Python is easy to learn"
print("Find 'easy':", sentence.find("easy"))
print("Find 'hard':", sentence.find("hard"))  # Returns -1 if not found
print("Count 'a':", sentence.count("a"))

Find 'easy': 10
Find 'hard': -1
Count 'a': 2


In [ ]:
# Replacing
print("Replace:", sentence.replace("easy", "powerful"))

Replace: Python is powerful to learn


In [ ]:
# Splitting and Joining
words = sentence.split()  # Split by space
print("Split:", words)

Split: ['Python', 'is', 'easy', 'to', 'learn']


In [ ]:
joined = " ".join(words)
print("Join:", joined)

Join: Python is easy to learn


In [ ]:
# Checking methods
print("Is digit:", "123".isdigit())
print("Is alpha:", "Hello".isalpha())
print("Is alphanumeric:", "Hello123".isalnum())
print("Starts with:", sentence.startswith("Python"))
print("Ends with:", sentence.endswith("learn"))

Is digit: True
Is alpha: True
Is alphanumeric: True
Starts with: True
Ends with: True


In [ ]:
# Practical example: Data cleaning
dirty_data = "  RAHUL KUMAR  "
clean_data = dirty_data.strip().title()
print("Cleaned:", clean_data)

Cleaned: Rahul Kumar


PRACTICE EXERCISE 6:
1. Create a string "Data Analysis" and print characters at index 0, 5, and -1
2. Extract the word "Analysis" using slicing
3. Convert the string to uppercase
4. Count how many times letter 'a' appears
5. Replace "Analysis" with "Science"

### 3. Concatenation

In [ ]:
# String concatenation with +
first = "Data"
second = "Science"
combined = first + " " + second
print("Concatenation:", combined)

Concatenation: Data Science


In [ ]:
# Concatenating multiple strings
greeting = "Hello" + " " + "Student" + "!"
print(greeting)

Hello Student!


In [ ]:
# Concatenation with variables
name = "Priya"
age = 21
# message = "Name: " + name + ", Age: " + age  # Error! Can't concat string with int
message = "Name: " + name + ", Age: " + str(age)
print(message)

Name: Priya, Age: 21


In [ ]:
# Better way: f-strings (formatted strings)
message_f = f"Name: {name}, Age: {age}"
print(message_f)

Name: Priya, Age: 21


In [ ]:
# Using format method
message_format = "Name: {}, Age: {}".format(name, age)
print(message_format)

Name: Priya, Age: 21


In [ ]:
# Practical example
student = "Amit"
marks = 85
percentage = 85.5
result = f"Student {student} scored {marks} marks with {percentage}% percentage"
print(result)

Student Amit scored 85 marks with 85.5% percentage


In [ ]:
# Multiple line concatenation
address = "House No: 123" + "\n" + "Street: MG Road" + "\n" + "City: Pune"
print(address)

House No: 123
Street: MG Road
City: Pune


PRACTICE EXERCISE 7:
1. Create two string variables with your first name and last name
2. Concatenate them with a space in between
3. Create variables for item name and price, then create a message like "Item: Laptop, Price: 50000"
4. Use f-string to create a message with your name and age

## Day 5: Operators

In [ ]:
### 1. Arithmetic Operators

# Addition
a = 10
b = 3
print("Addition:", a + b)

Addition: 13


In [ ]:
# Subtraction
print("Subtraction:", a - b)

Subtraction: 7


In [ ]:
#  Multiplication
print("Multiplication:", a * b)

Multiplication: 30


In [ ]:
#  Division (always returns float)
print("Division:", a / b)

Division: 3.3333333333333335


In [ ]:
#  Floor Division (returns integer, no decimal)
print("Floor Division:", a // b)

Floor Division: 3


In [ ]:
# Modulus (remainder)
print("Modulus:", a % b)

Modulus: 1


In [ ]:
# Exponentiation (power)
print("Exponentiation:", a ** b)  # 10^3 = 1000

Exponentiation: 1000


In [ ]:
# Real-world examples
total_marks = 450
num_subjects = 5
average = total_marks / num_subjects
print("Average marks:", average)


Average marks: 90.0


In [ ]:
price = 999
discount = 50
final_price = price - discount
print("Final price:", final_price)

Final price: 949


In [ ]:
# Calculate area of rectangle
length = 15
width = 10
area = length * width
print("Area:", area)

Area: 150


In [ ]:
# Check if number is even or odd
number = 17
remainder = number % 2
if remainder == 0:
    print(f"{number} is even")
else:
    print(f"{number} is odd")

17 is odd


PRACTICE EXERCISE 8:
1. Calculate the sum of 456 and 789
2. Divide 100 by 7 and print both regular division and floor division
3. Find the remainder when 50 is divided by 8
4. Calculate 2 to the power of 10
5. Calculate the average of three numbers: 85, 90, 78

### 2. Logical Operators: and, or, not

* Logical operators work with boolean values

* and: True if BOTH conditions are True

* or: True if AT LEAST ONE condition is True

* not: Reverses the boolean value

In [ ]:
# AND operator
print("True and True:", True and True)
print("True and False:", True and False)
print("False and False:", False and False)

True and True: True
True and False: False
False and False: False


In [ ]:
age = 20
has_id = True
can_vote = age >= 18 and has_id
print("Can vote:", can_vote)

Can vote: True


In [ ]:
# OR operator
print("True or True:", True or True)
print("True or False:", True or False)
print("False or False:", False or False)

True or True: True
True or False: True
False or False: False


In [ ]:
is_weekend = False
is_holiday = True
can_relax = is_weekend or is_holiday
print("Can relax:", can_relax)

Can relax: True


In [ ]:
# NOT operator
print("not True:", not True)
print("not False:", not False)

not True: False
not False: True


In [ ]:
is_raining = False
can_play_outside = not is_raining
print("Can play outside:", can_play_outside)

Can play outside: True


In [ ]:
is_raining = False

if not is_raining:
    print("You can go outside!")
else:
    print("Stay indoors.")

You can go outside!


In [ ]:
# Complex conditions
marks = 85
attendance = 80

In [ ]:
passed = marks >= 40 and attendance >= 75
print("Student passed:", passed)

Student passed: True


In [ ]:
scholarship = marks >= 90 or attendance >= 95
print("Gets scholarship:", scholarship)

Gets scholarship: False


In [ ]:
# Real-world example: Login system
username_correct = True
password_correct = True
account_active   = True

In [ ]:
login_success = username_correct and password_correct and account_active
print("Login successful:", login_success)

Login successful: True


In [ ]:
# E-commerce example
in_stock = True
price_affordable = True
delivery_available = False

can_buy = in_stock and price_affordable and delivery_available
print("Can buy product:", can_buy)

Can buy product: False


PRACTICE EXERCISE 9:
1. Create two boolean variables: is_sunny = True, is_warm = True
2. Use 'and' to check if it's both sunny AND warm
3. Create variables: has_bike = False, has_car = True
4. Use 'or' to check if person has any vehicle
5. Use 'not' to reverse the value of is_raining = False

### 3. Assignment Operators

In [ ]:
# Basic assignment
x = 10
print("x =", x)

x = 10


In [ ]:
# Add and assign (+=)
x = 10
x += 5  # Same as: x = x + 5
print("After +=:", x)

After +=: 15


In [ ]:
#  Subtract and assign (-=)
x = 10
x -= 3  # Same as: x = x - 3
print("After -=:", x)

After -=: 7


In [ ]:
# Multiply and assign (*=)
x = 10
x *= 2  # Same as: x = x * 2
print("After *=:", x)

After *=: 20


In [ ]:
# Divide and assign (/=)
x = 10
x /= 2  # Same as: x = x / 2
print("After /=:", x)

After /=: 5.0


In [ ]:
# Floor divide and assign (//=)
x = 10
x //= 3  # Same as: x = x // 3
print("After //=:", x)

After //=: 3


In [ ]:
# Modulus and assign (%=)
x = 10
x %= 3  # Same as: x = x % 3
print("After %=:", x)

After %=: 1


In [ ]:
# Exponent and assign (**=)
x = 2
x **= 3  # Same as: x = x ** 3
print("After **=:", x)

After **=: 8


In [ ]:
# Bank account
balance = 5000
print("Initial balance:", balance)

balance += 2000  # Deposit
print("After deposit:", balance)

balance -= 1500  # Withdrawal
print("After withdrawal:", balance)

Initial balance: 5000
After deposit: 7000
After withdrawal: 5500


In [ ]:
# Shopping cart
total = 0
total += 500
total += 1200
total += 300
print("Total cart value:", total)

Total cart value: 2000


In [ ]:
# Score tracking
score = 0
score += 10  # Level 1
score += 20  # Level 2
score += 15  # Level 3
print("Total score:", score)

Total score: 45


PRACTICE EXERCISE 10:
1. Create a variable count = 5
2. Use += to add 10 to it
3. Use -= to subtract 3 from it
4. Use *= to multiply it by 2
5. Print the final value

### 4. Comparison Operators

In [ ]:
'''Comparison operators return True or False
== : Equal to
!= : Not equal to
>  : Greater than
<  : Less than
>= : Greater than or equal to
<= : Less than or equal to
'''

'Comparison operators return True or False\n== : Equal to\n!= : Not equal to\n>  : Greater than\n<  : Less than\n>= : Greater than or equal to\n<= : Less than or equal to\n'

In [ ]:
# Equal to (==)
print("10 == 10:", 10 == 10)    # True
print("10 == 5:", 10 == 5)      # False
print("'hi' == 'hi':", "hi" == "hi")  # True

10 == 10: True
10 == 5: False
'hi' == 'hi': True


In [ ]:
# Not equal to (!=)
print("10 != 5:", 10 != 5)      # True
print("10 != 10:", 10 != 10)    # False


10 != 5: True
10 != 10: False


In [ ]:
# Greater than (>)
print("10 > 5:", 10 > 5)        # True
print("5 > 10:", 5 > 10)        # False

10 > 5: True
5 > 10: False


In [ ]:
# Less than (<)
print("5 < 10:", 5 < 10)        # True
print("10 < 5:", 10 < 5)        # False

5 < 10: True
10 < 5: False


# Real-world examples

In [ ]:
# Age verification
age = 17
is_adult = age >= 18
print("Is adult:", is_adult)

Is adult: False


In [ ]:
# Grade checking
marks = 85
passed = marks >= 40
print("Passed:", passed)

Passed: True


In [ ]:
grade_a = marks >= 90
print("Grade A:", grade_a)

Grade A: False


In [ ]:
# Price comparison
budget = 5000
item_price = 4500
can_afford = item_price <= budget
print("Can afford:", can_afford)

Can afford: True


In [ ]:
# Temperature check
temperature = 38
has_fever = temperature > 37
print("Has fever:", has_fever)

Has fever: True


In [ ]:
# Combining with logical operators
marks = 85
attendance = 80
scholarship = marks >= 90 and attendance >= 75
print("Eligible for scholarship:", scholarship)

Eligible for scholarship: False


In [ ]:
# Username validation
username = "student123"
valid_length = len(username) >= 6
print("Valid username length:", valid_length)

Valid username length: True


## PRACTICE EXERCISE 11:

1. Create two variables: marks1 = 75, marks2 = 80
2. Check if marks1 is equal to marks2
3. Check if marks1 is less than marks2
4. Create a variable age = 25, check if age >= 21
5. Create price = 1500, budget = 2000, check if price <= budget

In [ ]:
print("\n" + "="*50)
print("FINAL COMPREHENSIVE EXAMPLE")
print("="*50 + "\n")


FINAL COMPREHENSIVE EXAMPLE



In [ ]:
# Student information
student_name = "Rahul Sharma"
student_age = 21
student_email = "rahul.sharma@email.com"

In [ ]:
# Marks in different subjects
math_marks = 85
science_marks = 90
english_marks = 78
history_marks = 82
computer_marks = 95

In [ ]:
# Calculate total and average
total_marks = math_marks + science_marks + english_marks + history_marks + computer_marks
average_marks = total_marks / 5

In [ ]:
# Display student information
print("STUDENT REPORT CARD")
print("-" * 50)
print(f"Name: {student_name}")
print(f"Age: {student_age}")
print(f"Email: {student_email}")
print("-" * 50)

STUDENT REPORT CARD
--------------------------------------------------
Name: Rahul Sharma
Age: 21
Email: rahul.sharma@email.com
--------------------------------------------------


In [ ]:
# Display marks
print("SUBJECT-WISE MARKS:")
print(f"Mathematics: {math_marks}")
print(f"Science: {science_marks}")
print(f"English: {english_marks}")
print(f"History: {history_marks}")
print(f"Computer: {computer_marks}")
print("-" * 50)

SUBJECT-WISE MARKS:
Mathematics: 85
Science: 90
English: 78
History: 82
Computer: 95
--------------------------------------------------


In [ ]:
# Display results
print(f"Total Marks: {total_marks} / 500")
print(f"Average Marks: {average_marks:.2f}")
print(f"Percentage: {(average_marks):.2f}%")

Total Marks: 430 / 500
Average Marks: 86.00
Percentage: 86.00%


# Conditional Statements in Python - Making Decisions

## The Traffic Signal Story - Introduction


Imagine you're driving to college every morning. What happens at traffic signals?

🔴 RED Light → You STOP

🟡 YELLOW Light → You SLOW DOWN

🟢 GREEN Light → You GO

Your brain automatically makes decisions based on conditions.
This is exactly what conditional statements do in programming!

Real-life decisions:
- IF it's raining → Take umbrella
- IF marks >= 40 → Student passes
- IF age >= 18 → Can vote
- IF price <= budget → Buy the product

Today we'll teach Python to make intelligent decisions!

-------------------

## Structure of Conditional Statements

BASIC STRUCTURE:

if condition:
    
    # code to execute if condition is True

    # This block runs only when condition is True

SYNTAX RULES:
1. 'if' keyword in lowercase
2. Condition (returns True or False)
3. Colon : at the end
4. Indentation (4 spaces or 1 tab) is MANDATORY
5. All code in the if-block must be indented equally

Think of indentation as showing "this code belongs to if statement"

In [ ]:
# Example 1: Basic if statement

age = 20

if age >= 18:
    print("You are an adult")
    print("You can vote")

print("This line always executes")

You are an adult
You can vote
This line always executes


In [ ]:
# Example 2: Checking temperature
temperature = 38

if temperature > 37:
    print("You have fever!")
    print("Please consult a doctor")


You have fever!
Please consult a doctor


In [ ]:
# Example 3: variables and comparison
marks = 85

if marks >= 40:
    print("Congratulations! You passed")

if marks >= 90:
    print("Excellent! You got A+ grade")

Congratulations! You passed


In [ ]:
# Example 4: String comparison
username = "student123"

if username == "student123":
    print("Welcome back, Student!")

Welcome back, Student!


In [ ]:
# Example 5: Using logical operators with if
marks = 85
attendance = 80

if marks >= 40 and attendance >= 75:
    print("You are eligible for final exam")

You are eligible for final exam


PRACTICE EXERCISE 1:
1. Create a variable price = 1500 and budget = 2000
2. Use if to check if price <= budget, print "You can buy this product"
3. Create a variable is_raining = True
4. Use if to check is_raining, print "Take an umbrella"
5. Create age = 16, use if to check if age >= 18, print "You can get driving license"

## 2. if-else Statement

In [ ]:
"""
The 'if-else' statement:
- Checks a condition
- If True, executes if-block
- If False, executes else-block
- One of the two blocks ALWAYS executes

Structure:
if condition:
    # executes when condition is True
else:
    # executes when condition is False
"""


"\nThe 'if-else' statement:\n- Checks a condition\n- If True, executes if-block\n- If False, executes else-block\n- One of the two blocks ALWAYS executes\n\nStructure:\nif condition:\n    # executes when condition is True\nelse:\n    # executes when condition is False\n"

In [ ]:
# Example 1: Basic if-else
age = 16

if age >= 18:
    print("You are an adult")
    print("You can vote")
else:
    print("You are a minor")
    print("You cannot vote yet")

You are a minor
You cannot vote yet


In [ ]:
# Example 2: Even or Odd
number = 17

if number % 2 == 0:
    print(f"{number} is an EVEN number")
else:
    print(f"{number} is an ODD number")

17 is an ODD number


In [ ]:
# Example 3: Pass or Fail
marks = 35

if marks >= 40:
    print("Result: PASSED")
    print("Congratulations!")
else:
    print("Result: FAILED")
    print("Better luck next time")

Result: FAILED
Better luck next time


In [ ]:
# Example 4: Product availability
in_stock = False

if in_stock:
    print("Product is available")
    print("You can place order")
else:
    print("Product is out of stock")
    print("Please check back later")

Product is out of stock
Please check back later


In [ ]:
# Example 5: Temperature check
temperature = 36

if temperature > 37:
    print("You have fever")
else:
    print("Your temperature is normal")

Your temperature is normal


In [ ]:
# Example 6: Using string methods from previous notes
password = "Python123"

if len(password) >= 8:
    print("Strong password")
else:
    print("Weak password - Use at least 8 characters")

Strong password


In [ ]:
"""
PRACTICE EXERCISE 2:
1. Create a variable marks = 55
2. Use if-else to check if marks >= 40, print "Passed" or "Failed"
3. Create a variable age = 25
4. Use if-else to check if age >= 21, print "Can drive car" or "Cannot drive car"
5. Create number = 50, check if divisible by 5, print "Divisible" or "Not divisible"
"""

'\nPRACTICE EXERCISE 2:\n1. Create a variable marks = 55\n2. Use if-else to check if marks >= 40, print "Passed" or "Failed"\n3. Create a variable age = 25\n4. Use if-else to check if age >= 21, print "Can drive car" or "Cannot drive car"\n5. Create number = 50, check if divisible by 5, print "Divisible" or "Not divisible"\n'

## 3. elif Statement (else-if)

"""
The 'elif' statement:
- Used for multiple conditions
- Checks conditions one by one from top to bottom
- Executes the FIRST True condition and skips rest
- Can have multiple elif statements
- Optional else at the end as default case

Structure:


```
#
if condition1:
    # executes if condition1 is True
elif condition2:
    # executes if condition1 is False and condition2 is True
elif condition3:
    # executes if condition1 and condition2 are False and condition3 is True
else:
    # executes if all conditions are False
```



In [ ]:
# Example 1: Traffic Signal (our opening story!)
signal = "GREEN"

if signal == "GREEN":
    print("GO - Drive ahead")
elif signal == "YELLOW":
    print("SLOW DOWN - Prepare to stop")
elif signal == "RED":
    print("STOP - Wait for green")
else:
    print("Invalid signal")

GO - Drive ahead


In [ ]:
# Example 2: Grade calculation
marks = 85

if marks >= 90:
    print("Grade: A+")
    print("Outstanding performance!")
elif marks >= 80:
    print("Grade: A")
    print("Excellent work!")
elif marks >= 70:
    print("Grade: B")
    print("Good job!")
elif marks >= 60:
    print("Grade: C")
    print("Satisfactory")
elif marks >= 40:
    print("Grade: D")
    print("Just passed")
else:
    print("Grade: F")
    print("Failed - Need to work harder")

Grade: A
Excellent work!


In [ ]:
# Example 3: Day of the week
day = 1

if day == 1:
    print("Monday")
elif day == 2:
    print("Tuesday")
elif day == 3:
    print("Wednesday")
elif day == 4:
    print("Thursday")
elif day == 5:
    print("Friday")
elif day == 6:
    print("Saturday")
elif day == 7:
    print("Sunday")
else:
    print("Invalid day number")

Monday


In [ ]:
# Example 4: Age categories
age = 45

if age < 13:
    print("You are a child")
elif age < 20:
    print("You are a teenager")
elif age < 60:
    print("You are an adult")
else:
    print("You are a senior citizen")

You are an adult


In [ ]:
# Example 5: Temperature categories
temperature = 42

if temperature >= 40:
    print("Extremely hot - Stay indoors")
elif temperature >= 30:
    print("Hot - Use air conditioning")
elif temperature >= 20:
    print("Pleasant - Enjoy the weather")
elif temperature >= 10:
    print("Cool - Wear light jacket")
else:
    print("Cold - Wear warm clothes")


Extremely hot - Stay indoors




```
PRACTICE EXERCISE 3:
1. Create a variable time = 14 (24-hour format)
2. Use if-elif-else to print:
   - "Good Morning" if time < 12
   - "Good Afternoon" if time < 17
   - "Good Evening" if time < 21
   - "Good Night" otherwise
3. Create percentage = 75, categorize as:
   - Distinction (>= 75)
   - First Class (>= 60)
   - Second Class (>= 50)
   - Pass (>= 40)
   - Fail (< 40)
```



In [ ]:
## 4. Complete Examples with Previous Concepts

# Example 1: Using variables and operators from previous notes
print("\n" + "="*50)
print("EXAMPLE 1: CALCULATOR WITH DECISIONS")
print("="*50)

num1 = 10
num2 = 5
operation = "add"

if operation == "add":
    result = num1 + num2
    print(f"{num1} + {num2} = {result}")
elif operation == "subtract":
    result = num1 - num2
    print(f"{num1} - {num2} = {result}")
elif operation == "multiply":
    result = num1 * num2
    print(f"{num1} * {num2} = {result}")
elif operation == "divide":
    if num2 != 0:  # Nested if to check division by zero
        result = num1 / num2
        print(f"{num1} / {num2} = {result}")
    else:
        print("Error: Cannot divide by zero")
else:
    print("Invalid operation")


EXAMPLE 1: CALCULATOR WITH DECISIONS
10 + 5 = 15


In [ ]:
# Example 2: Using strings and type casting from previous notes

print("\n" + "="*50)
print("EXAMPLE 2: USER LOGIN SYSTEM")
print("="*50)

stored_username = "student123"
stored_password = "python2024"

input_username = "student123"
input_password = "python2024"

if input_username == stored_username and input_password == stored_password:
    print("Login Successful!")
    print(f"Welcome, {input_username.upper()}")
else:
    print("Login Failed!")
    print("Invalid username or password")


EXAMPLE 2: USER LOGIN SYSTEM
Login Successful!
Welcome, STUDENT123


In [ ]:
# Example 3: Using lists from previous notes
print("\n" + "="*50)
print("EXAMPLE 3: SHOPPING CART")
print("="*50)

cart_items = ["Laptop", "Mouse", "Keyboard"]
cart_count = len(cart_items)

if cart_count == 0:
    print("Your cart is empty")
    print("Start shopping!")
elif cart_count <= 3:
    print(f"You have {cart_count} items in cart")
    print("Items:", cart_items)
else:
    print(f"You have {cart_count} items in cart")
    print("You get free delivery!")


EXAMPLE 3: SHOPPING CART
You have 3 items in cart
Items: ['Laptop', 'Mouse', 'Keyboard']


In [ ]:
## 5. REAL-WORLD PROJECT 1: Student Grading System

print("\n" + "="*60)
print("PROJECT 1: STUDENT GRADING SYSTEM")
print("="*60)

# Student information (using variables from Day 3)
student_name = "Rahul Sharma"
student_roll = 101

# Marks in different subjects (using integers from Day 3)
math_marks = 85
science_marks = 90
english_marks = 78
history_marks = 82
computer_marks = 95

# Calculate total and average (using arithmetic operators from Day 5)
total_marks = math_marks + science_marks + english_marks + history_marks + computer_marks
average_marks = total_marks / 5
percentage = average_marks  # Since each subject is out of 100

# Display student info (using f-strings from Day 4)
print(f"\nStudent Name: {student_name}")
print(f"Roll Number: {student_roll}")
print("-" * 60)

# Display marks (using variables)
print("SUBJECT-WISE MARKS:")
print(f"Mathematics: {math_marks}")
print(f"Science: {science_marks}")
print(f"English: {english_marks}")
print(f"History: {history_marks}")
print(f"Computer: {computer_marks}")
print("-" * 60)

# Calculate and display totals (using operators)
print(f"Total Marks: {total_marks} / 500")
print(f"Percentage: {percentage:.2f}%")

# Determine grade using if-elif-else
print("-" * 60)
if percentage >= 90:
    grade = "A+"
    remarks = "Outstanding Performance!"
elif percentage >= 80:
    grade = "A"
    remarks = "Excellent Work!"
elif percentage >= 70:
    grade = "B"
    remarks = "Good Job!"
elif percentage >= 60:
    grade = "C"
    remarks = "Satisfactory"
elif percentage >= 40:
    grade = "D"
    remarks = "Need Improvement"
else:
    grade = "F"
    remarks = "Failed - Work Harder"

print(f"Grade: {grade}")
print(f"Remarks: {remarks}")

# Check pass/fail using if-else
print("-" * 60)
if percentage >= 40:
    print("RESULT: ✓ PASSED")

    # Check for distinction using nested if
    if percentage >= 75:
        print("STATUS: PASSED WITH DISTINCTION")
    elif percentage >= 60:
        print("STATUS: PASSED WITH FIRST CLASS")
    else:
        print("STATUS: PASSED")

    # Check scholarship eligibility (using logical operators from Day 5)
    if percentage >= 85 and math_marks >= 80 and science_marks >= 80:
        print("SCHOLARSHIP: ✓ ELIGIBLE")
        print("Congratulations! You qualify for Merit Scholarship")
    else:
        print("SCHOLARSHIP: ✗ NOT ELIGIBLE")
else:
    print("RESULT: ✗ FAILED")
    print("Please work harder and try again")

# Subject-wise analysis
print("-" * 60)
print("SUBJECT-WISE ANALYSIS:")

if math_marks < 40:
    print("⚠ Mathematics: FAIL - Need to improve")
elif math_marks >= 80:
    print("✓ Mathematics: EXCELLENT")
else:
    print("✓ Mathematics: PASS")

if science_marks < 40:
    print("⚠ Science: FAIL - Need to improve")
elif science_marks >= 80:
    print("✓ Science: EXCELLENT")
else:
    print("✓ Science: PASS")

if english_marks < 40:
    print("⚠ English: FAIL - Need to improve")
elif english_marks >= 80:
    print("✓ English: EXCELLENT")
else:
    print("✓ English: PASS")

print("="*60)



PROJECT 1: STUDENT GRADING SYSTEM

Student Name: Rahul Sharma
Roll Number: 101
------------------------------------------------------------
SUBJECT-WISE MARKS:
Mathematics: 85
Science: 90
English: 78
History: 82
Computer: 95
------------------------------------------------------------
Total Marks: 430 / 500
Percentage: 86.00%
------------------------------------------------------------
Grade: A
Remarks: Excellent Work!
------------------------------------------------------------
RESULT: ✓ PASSED
STATUS: PASSED WITH DISTINCTION
SCHOLARSHIP: ✓ ELIGIBLE
Congratulations! You qualify for Merit Scholarship
------------------------------------------------------------
SUBJECT-WISE ANALYSIS:
✓ Mathematics: EXCELLENT
✓ Science: EXCELLENT
✓ English: PASS


In [ ]:
age = int(input("Enter your age: "))

if age < 5:
    print("Ticket Price: ₹0 — Free Entry")
elif age <= 18:
    print("Ticket Price: ₹100 — Child Ticket")
elif age <= 60:
    print("Ticket Price: ₹250 — Adult Ticket")
else:
    print("Ticket Price: ₹150 — Senior Citizen Ticket")


Ticket Price: ₹100 — Child Ticket


DAY 7: LISTS & TUPLES - STUDENT GRADE MANAGER PROJECT
=====================================================
Topics Covered:
- Understanding Lists
- Indexing and slicing in lists
- List methods: append(), extend(), insert(), remove(), pop(), clear(), index(), count(), sort(), reverse()
- Tuples basics
- Real-world application with if-elif-else

In [ ]:
print("="*70)
print("     DAY 7: MASTERING LISTS & TUPLES")
print("="*70)

# ============================================================================
# PART 1: UNDERSTANDING LISTS BASICS
# ============================================================================
print("\n📚 PART 1: UNDERSTANDING LISTS")
print("-"*70)

# Creating a list of subjects
subjects = ["Math", "Science", "English", "History", "Computer"]
print(f"Subjects List: {subjects}")
print(f"Type: {type(subjects)}")
print(f"Number of subjects: {len(subjects)}")


     DAY 7: MASTERING LISTS & TUPLES

📚 PART 1: UNDERSTANDING LISTS
----------------------------------------------------------------------
Subjects List: ['Math', 'Science', 'English', 'History', 'Computer']
Type: <class 'list'>
Number of subjects: 5


In [ ]:
# ============================================================================
# PART 2: INDEXING AND SLICING
# ============================================================================
print("\n📚 PART 2: INDEXING AND SLICING")
print("-"*70)

# Student marks for 5 subjects
rahul_marks = [85, 90, 78, 82, 95]
print(f"Rahul's Marks: {rahul_marks}")

# Indexing - Accessing individual elements
print(f"\nFirst subject marks (index 0): {rahul_marks[0]}")
print(f"Last subject marks (index -1): {rahul_marks[-1]}")
print(f"Third subject marks (index 2): {rahul_marks[2]}")

# Slicing - Accessing multiple elements
print(f"\nFirst 3 subjects marks: {rahul_marks[0:3]}")
print(f"Last 2 subjects marks: {rahul_marks[3:5]}")
print(f"All marks from index 2: {rahul_marks[2:]}")
print(f"Marks up to index 3: {rahul_marks[:3]}")


📚 PART 2: INDEXING AND SLICING
----------------------------------------------------------------------
Rahul's Marks: [85, 90, 78, 82, 95]

First subject marks (index 0): 85
Last subject marks (index -1): 95
Third subject marks (index 2): 78

First 3 subjects marks: [85, 90, 78]
Last 2 subjects marks: [82, 95]
All marks from index 2: [78, 82, 95]
Marks up to index 3: [85, 90, 78]


In [ ]:
# ============================================================================
# PART 3: LIST METHODS - ADDING ELEMENTS
# ============================================================================
print("\n📚 PART 3: LIST METHODS - ADDING ELEMENTS")
print("-"*70)

# Starting with Priya's marks for 3 subjects
priya_marks = [88, 92, 85]
print(f"Priya's initial marks: {priya_marks}")

# append() - Add one element at the end
priya_marks.append(90)
print(f"After append(90): {priya_marks}")

# extend() - Add multiple elements at the end
priya_marks.extend([87])
print(f"After extend([87]): {priya_marks}")

# insert() - Add element at specific position
priya_marks.insert(2, 94)  # Insert 94 at index 2
print(f"After insert(2, 94): {priya_marks}")


📚 PART 3: LIST METHODS - ADDING ELEMENTS
----------------------------------------------------------------------
Priya's initial marks: [88, 92, 85]
After append(90): [88, 92, 85, 90]
After extend([87]): [88, 92, 85, 90, 87]
After insert(2, 94): [88, 92, 94, 85, 90, 87]


In [ ]:
# ============================================================================
# PART 4: LIST METHODS - REMOVING ELEMENTS
# ============================================================================
print("\n📚 PART 4: LIST METHODS - REMOVING ELEMENTS")
print("-"*70)

# Arjun's marks with a mistake
arjun_marks = [75, 80, 94, 85, 78, 88]
print(f"Arjun's marks (with extra entry): {arjun_marks}")

# remove() - Remove first occurrence of value
arjun_marks.remove(94)  # Remove the extra 94
print(f"After remove(94): {arjun_marks}")

# pop() - Remove and return element at index
removed_mark = arjun_marks.pop()  # Removes last element
print(f"After pop(): {arjun_marks}")
print(f"Removed mark: {removed_mark}")

# pop() with index
removed_mark2 = arjun_marks.pop(1)  # Removes element at index 1
print(f"After pop(1): {arjun_marks}")
print(f"Removed mark: {removed_mark2}")


📚 PART 4: LIST METHODS - REMOVING ELEMENTS
----------------------------------------------------------------------
Arjun's marks (with extra entry): [75, 80, 94, 85, 78, 88]
After remove(94): [75, 80, 85, 78, 88]
After pop(): [75, 80, 85, 78]
Removed mark: 88
After pop(1): [75, 85, 78]
Removed mark: 80


In [ ]:
# ============================================================================
# PART 5: LIST METHODS - UTILITY METHODS
# ============================================================================
print("\n PART 5: LIST METHODS - UTILITY METHODS")
print("-"*70)

# Sample marks for demonstration
demo_marks = [85, 90, 85, 78, 92, 85]
print(f"Demo marks: {demo_marks}")

# count() - Count occurrences of a value
count_85 = demo_marks.count(85)
print(f"Number of times 85 appears: {count_85}")

# index() - Find index of first occurrence
index_90 = demo_marks.index(90)
print(f"Index of first 90: {index_90}")

# sort() - Sort the list in ascending order
demo_marks.sort()
print(f"After sort(): {demo_marks}")

# sort(reverse=True) - Sort in descending order
demo_marks.sort(reverse=True)
print(f"After sort(reverse=True): {demo_marks}")

# reverse() - Reverse the list order
demo_marks.reverse()
print(f"After reverse(): {demo_marks}")


 PART 5: LIST METHODS - UTILITY METHODS
----------------------------------------------------------------------
Demo marks: [85, 90, 85, 78, 92, 85]
Number of times 85 appears: 3
Index of first 90: 1
After sort(): [78, 85, 85, 85, 90, 92]
After sort(reverse=True): [92, 90, 85, 85, 85, 78]
After reverse(): [78, 85, 85, 85, 90, 92]


In [ ]:
# ============================================================================
# PART 6: TUPLES - IMMUTABLE LISTS
# ============================================================================
print("\n📚 PART 6: UNDERSTANDING TUPLES")
print("-"*70)

# Creating tuples - fixed student information
student_info = ("Rahul Sharma", 101, "Class 10-A")
print(f"Student Info Tuple: {student_info}")
print(f"Type: {type(student_info)}")

# Accessing tuple elements
print(f"Student Name: {student_info[0]}")
print(f"Roll Number: {student_info[1]}")
print(f"Class: {student_info[2]}")

# Grade boundaries (fixed values)
grade_boundaries = (90, 80, 70, 60, 40)
print(f"\nGrade Boundaries: {grade_boundaries}")


📚 PART 6: UNDERSTANDING TUPLES
----------------------------------------------------------------------
Student Info Tuple: ('Rahul Sharma', 101, 'Class 10-A')
Type: <class 'tuple'>
Student Name: Rahul Sharma
Roll Number: 101
Class: Class 10-A

Grade Boundaries: (90, 80, 70, 60, 40)


In [ ]:
# ============================================================================
# MINI PROJECT: COMPREHENSIVE STUDENT GRADE MANAGER
# ============================================================================
print("\n" + "="*70)
print("MINI PROJECT: STUDENT GRADE MANAGER")
print("="*70)

# Student Information (Tuple - Immutable)
student = ("Ananya Verma", 105, "Class 10-B")
print(f"\nStudent Name: {student[0]}")
print(f"Roll Number: {student[1]}")
print(f"Class: {student[2]}")
print("-"*70)

# Subject names (List)
subjects_list = ["Math", "Science", "English", "History", "Computer"]

# Student marks (List - Mutable)
marks_list = [88, 92, 85, 90, 94]

print("\n ORIGINAL SUBJECT-WISE MARKS:")
print(f"{subjects_list[0]}: {marks_list[0]}")
print(f"{subjects_list[1]}: {marks_list[1]}")
print(f"{subjects_list[2]}: {marks_list[2]}")
print(f"{subjects_list[3]}: {marks_list[3]}")
print(f"{subjects_list[4]}: {marks_list[4]}")

# Calculate totals using slicing
total_marks = marks_list[0] + marks_list[1] + marks_list[2] + marks_list[3] + marks_list[4]
average_marks = total_marks / 5
percentage = average_marks

print("-"*70)
print(f"Total Marks: {total_marks} / 500")
print(f"Average Marks: {average_marks:.2f}")
print(f"Percentage: {percentage:.2f}%")

# Grade determination using if-elif-else
print("-"*70)
if percentage >= 90:
    grade = "A+"
    remarks = "Outstanding!"
elif percentage >= 80:
    grade = "A"
    remarks = "Excellent!"
elif percentage >= 70:
    grade = "B"
    remarks = "Good!"
elif percentage >= 60:
    grade = "C"
    remarks = "Satisfactory"
else:
    grade = "D"
    remarks = "Need Improvement"

print(f"GRADE: {grade}")
print(f"REMARKS: {remarks}")

# Find highest and lowest marks using list methods
print("-"*70)
print("PERFORMANCE ANALYSIS:")

# Create a copy for sorting
sorted_marks = [marks_list[0], marks_list[1], marks_list[2], marks_list[3], marks_list[4]]
sorted_marks.sort()

lowest_mark = sorted_marks[0]
highest_mark = sorted_marks[-1]

print(f"Highest Marks: {highest_mark}")
print(f"Lowest Marks: {lowest_mark}")

# Find which subject has highest and lowest
if marks_list[0] == highest_mark:
    best_subject = subjects_list[0]
elif marks_list[1] == highest_mark:
    best_subject = subjects_list[1]
elif marks_list[2] == highest_mark:
    best_subject = subjects_list[2]
elif marks_list[3] == highest_mark:
    best_subject = subjects_list[3]
else:
    best_subject = subjects_list[4]

if marks_list[0] == lowest_mark:
    weak_subject = subjects_list[0]
elif marks_list[1] == lowest_mark:
    weak_subject = subjects_list[1]
elif marks_list[2] == lowest_mark:
    weak_subject = subjects_list[2]
elif marks_list[3] == lowest_mark:
    weak_subject = subjects_list[3]
else:
    weak_subject = subjects_list[4]

print(f"Best Subject: {best_subject} ({highest_mark})")
print(f"Needs Focus: {weak_subject} ({lowest_mark})")

# Check subject-wise excellence
print("-"*70)
print("SUBJECT-WISE EXCELLENCE:")

if marks_list[0] >= 90:
    print(f"✓ {subjects_list[0]}: OUTSTANDING")
elif marks_list[0] >= 75:
    print(f"✓ {subjects_list[0]}: EXCELLENT")
else:
    print(f"• {subjects_list[0]}: GOOD")

if marks_list[1] >= 90:
    print(f"✓ {subjects_list[1]}: OUTSTANDING")
elif marks_list[1] >= 75:
    print(f"✓ {subjects_list[1]}: EXCELLENT")
else:
    print(f"• {subjects_list[1]}: GOOD")

if marks_list[2] >= 90:
    print(f"✓ {subjects_list[2]}: OUTSTANDING")
elif marks_list[2] >= 75:
    print(f"✓ {subjects_list[2]}: EXCELLENT")
else:
    print(f"• {subjects_list[2]}: GOOD")

# Count outstanding performances
outstanding_count = 0
if marks_list[0] >= 90:
    outstanding_count = outstanding_count + 1
if marks_list[1] >= 90:
    outstanding_count = outstanding_count + 1
if marks_list[2] >= 90:
    outstanding_count = outstanding_count + 1
if marks_list[3] >= 90:
    outstanding_count = outstanding_count + 1
if marks_list[4] >= 90:
    outstanding_count = outstanding_count + 1

print("-"*70)
print(f" Outstanding Subjects Count: {outstanding_count}")

# Scholarship eligibility
if percentage >= 85 and outstanding_count >= 2:
    print("SCHOLARSHIP: ELIGIBLE")
    print("Congratulations! You qualify for Merit Scholarship!")
else:
    print("SCHOLARSHIP: Keep working hard for next year!")

print("\n" + "="*70)
print("     END OF DAY 7 - LISTS & TUPLES MASTERY")
print("="*70)


MINI PROJECT: STUDENT GRADE MANAGER

Student Name: Ananya Verma
Roll Number: 105
Class: Class 10-B
----------------------------------------------------------------------

 ORIGINAL SUBJECT-WISE MARKS:
Math: 88
Science: 92
English: 85
History: 90
Computer: 94
----------------------------------------------------------------------
Total Marks: 449 / 500
Average Marks: 89.80
Percentage: 89.80%
----------------------------------------------------------------------
GRADE: A
REMARKS: Excellent!
----------------------------------------------------------------------
PERFORMANCE ANALYSIS:
Highest Marks: 94
Lowest Marks: 85
Best Subject: Computer (94)
Needs Focus: English (85)
----------------------------------------------------------------------
SUBJECT-WISE EXCELLENCE:
✓ Math: EXCELLENT
✓ Science: OUTSTANDING
✓ English: EXCELLENT
----------------------------------------------------------------------
 Outstanding Subjects Count: 3
SCHOLARSHIP: ELIGIBLE
Congratulations! You qualify for Merit Sch


DAY 8: LISTS vs TUPLES - UNDERSTANDING THE DIFFERENCE
======================================================
Real-World Scenarios and Technical Deep Dive


In [ ]:
print("="*80)
print("     DAY 8: LISTS vs TUPLES - WHEN TO USE WHAT?")
print("="*80)

# ============================================================================
# REAL-WORLD SCENARIO 1: SHOPPING AT A GROCERY STORE
# ============================================================================

print("\n SCENARIO 1: GROCERY SHOPPING")
print("-"*80)
print("""
YOU (Human): I'm going to the store. Let me write my shopping list:
- Milk
- Bread
- Eggs
- Rice
- Oil

Wait! I forgot to add "Butter". Let me add it to my list.
Oh, I already have rice at home. Let me cross it out.
Actually, let me rearrange - I'll pick dairy items first.

MACHINE: This is a LIST! Your shopping list CHANGES - you add, remove, reorder.
""")

# Human behavior: Shopping list that changes
shopping_list = ["Milk", "Bread", "Eggs", "Rice", "Oil"]
print(f"\nInitial Shopping List: {shopping_list}")

# Adding forgotten item
shopping_list.append("Butter")
print(f"After adding Butter: {shopping_list}")

# Removing item (already have at home)
shopping_list.remove("Rice")
print(f"After removing Rice: {shopping_list}")

# Reordering items
shopping_list.sort()
print(f"After sorting (organized): {shopping_list}")

print("\n USE LIST: When data CHANGES - add, remove, modify, reorder")


     DAY 8: LISTS vs TUPLES - WHEN TO USE WHAT?

 SCENARIO 1: GROCERY SHOPPING
--------------------------------------------------------------------------------

YOU (Human): I'm going to the store. Let me write my shopping list:
- Milk
- Bread
- Eggs
- Rice
- Oil

Wait! I forgot to add "Butter". Let me add it to my list.
Oh, I already have rice at home. Let me cross it out.
Actually, let me rearrange - I'll pick dairy items first.

MACHINE: This is a LIST! Your shopping list CHANGES - you add, remove, reorder.


Initial Shopping List: ['Milk', 'Bread', 'Eggs', 'Rice', 'Oil']
After adding Butter: ['Milk', 'Bread', 'Eggs', 'Rice', 'Oil', 'Butter']
After removing Rice: ['Milk', 'Bread', 'Eggs', 'Oil', 'Butter']
After sorting (organized): ['Bread', 'Butter', 'Eggs', 'Milk', 'Oil']

 USE LIST: When data CHANGES - add, remove, modify, reorder


In [ ]:
# ============================================================================
# REAL-WORLD SCENARIO 2: YOUR IDENTITY CARD (AADHAAR/PAN)
# ============================================================================

print("\n" + "="*80)
print(" SCENARIO 2: YOUR IDENTITY CARD")
print("-"*80)

print("""
YOU (Human): My identity information:
- Name: Rahul Sharma
- Date of Birth: 15-08-2005
- Aadhaar: 1234-5678-9012
- Blood Group: O+

Can I change my name on Aadhaar? NO (without official process)
Can I change my date of birth? NO (it's permanent)
Can I change my Aadhaar number? NO (it's fixed for life)
Can I change my blood group? NO (biological fact)

MACHINE: This is a TUPLE! Your identity is FIXED - cannot be changed easily.
""")

# Machine behavior: Identity information that's fixed
identity_info = ("Rahul Sharma", "15-08-2005", "1234-5678-9012", "O+")
print(f"\nIdentity Information: {identity_info}")
print(f"Name: {identity_info[0]}")
print(f"Date of Birth: {identity_info[1]}")
print(f"Aadhaar Number: {identity_info[2]}")
print(f"Blood Group: {identity_info[3]}")

# Try to change (will show error in explanation)
print("\n Trying to change name: identity_info[0] = 'New Name'")
print("   ERROR! Tuples are IMMUTABLE - cannot be changed!")

print("\n USE TUPLE: When data is PERMANENT - identity, coordinates, dates")



 SCENARIO 2: YOUR IDENTITY CARD
--------------------------------------------------------------------------------

YOU (Human): My identity information:
- Name: Rahul Sharma
- Date of Birth: 15-08-2005
- Aadhaar: 1234-5678-9012
- Blood Group: O+

Can I change my name on Aadhaar? NO (without official process)
Can I change my date of birth? NO (it's permanent)
Can I change my Aadhaar number? NO (it's fixed for life)
Can I change my blood group? NO (biological fact)

MACHINE: This is a TUPLE! Your identity is FIXED - cannot be changed easily.


Identity Information: ('Rahul Sharma', '15-08-2005', '1234-5678-9012', 'O+')
Name: Rahul Sharma
Date of Birth: 15-08-2005
Aadhaar Number: 1234-5678-9012
Blood Group: O+

 Trying to change name: identity_info[0] = 'New Name'
   ERROR! Tuples are IMMUTABLE - cannot be changed!

 USE TUPLE: When data is PERMANENT - identity, coordinates, dates


In [ ]:
# ============================================================================
# REAL-WORLD SCENARIO 3: RESTAURANT MENU vs DAILY ORDERS
# ============================================================================
print("\n" + "="*80)
print(" SCENARIO 3: RESTAURANT - MENU vs ORDERS")
print("-"*80)
print("""
RESTAURANT OWNER:

FIXED MENU ITEMS (don't change daily):
- Item 1: Paneer Tikka - ₹250
- Item 2: Dal Makhani - ₹180
- Item 3: Naan - ₹40
→ These are TUPLES (menu stays same)

TODAY'S ORDERS (keep changing):
- Order 1: Paneer Tikka
- Order 2: Dal Makhani
- New order comes: Naan
- Order cancelled: Dal Makhani
→ This is a LIST (orders keep changing)
""")

# Menu items (fixed prices)
menu_item_1 = ("Paneer Tikka", 250)
menu_item_2 = ("Dal Makhani", 180)
menu_item_3 = ("Naan", 40)

print(f"\nMenu Item 1: {menu_item_1[0]} - ₹{menu_item_1[1]}")
print(f"Menu Item 2: {menu_item_2[0]} - ₹{menu_item_2[1]}")
print(f"Menu Item 3: {menu_item_3[0]} - ₹{menu_item_3[1]}")

# Today's orders (keep changing)
todays_orders = ["Paneer Tikka", "Dal Makhani"]
print(f"\nInitial Orders: {todays_orders}")

todays_orders.append("Naan")
print(f"New order added: {todays_orders}")

todays_orders.remove("Dal Makhani")
print(f"Order cancelled: {todays_orders}")

print("\n MENU = TUPLE (fixed), ORDERS = LIST (dynamic)")



 SCENARIO 3: RESTAURANT - MENU vs ORDERS
--------------------------------------------------------------------------------

RESTAURANT OWNER: 

FIXED MENU ITEMS (don't change daily):
- Item 1: Paneer Tikka - ₹250
- Item 2: Dal Makhani - ₹180
- Item 3: Naan - ₹40
→ These are TUPLES (menu stays same)

TODAY'S ORDERS (keep changing):
- Order 1: Paneer Tikka
- Order 2: Dal Makhani
- New order comes: Naan
- Order cancelled: Dal Makhani
→ This is a LIST (orders keep changing)


Menu Item 1: Paneer Tikka - ₹250
Menu Item 2: Dal Makhani - ₹180
Menu Item 3: Naan - ₹40

Initial Orders: ['Paneer Tikka', 'Dal Makhani']
New order added: ['Paneer Tikka', 'Dal Makhani', 'Naan']
Order cancelled: ['Paneer Tikka', 'Naan']

 MENU = TUPLE (fixed), ORDERS = LIST (dynamic)


In [ ]:
# ============================================================================
# TECHNICAL CONCEPT 1: MUTABILITY
# ============================================================================
print("\n" + "="*80)
print(" CONCEPT 1: MUTABILITY - CAN DATA BE CHANGED?")
print("="*80)

print("\n LISTS are MUTABLE (Can be changed)")
print("-"*80)
mutable_list = [10, 20, 30, 40, 50]
print(f"Original List: {mutable_list}")

# We CAN change list elements
mutable_list[0] = 100
print(f"After changing index 0: {mutable_list}")

mutable_list.append(60)
print(f"After appending 60: {mutable_list}")

mutable_list.remove(30)
print(f"After removing 30: {mutable_list}")

print("\n Lists allow: modify, add, remove, sort, reverse")

print("\n TUPLES are IMMUTABLE (Cannot be changed)")
print("-"*80)
immutable_tuple = (10, 20, 30, 40, 50)
print(f"Original Tuple: {immutable_tuple}")

print("\n❌ CANNOT do these operations on tuples:")
print("   • immutable_tuple[0] = 100  → ERROR!")
print("   • immutable_tuple.append(60) → ERROR!")
print("   • immutable_tuple.remove(30) → ERROR!")
print("   • immutable_tuple.sort()     → ERROR!")

print("\n Tuples allow: access, slice, count, index ONLY")

# What you CAN do with tuples
print(f"\nAccess element: {immutable_tuple[0]}")
print(f"Slice tuple: {immutable_tuple[1:4]}")
print(f"Count occurrences: {immutable_tuple.count(20)}")
print(f"Find index: {immutable_tuple.index(30)}")

# ============================================================================
# TECHNICAL CONCEPT 2: SYNTAX
# ============================================================================
print("\n" + "="*80)
print(" CONCEPT 2: SYNTAX - HOW TO CREATE THEM?")
print("="*80)

print("\n LISTS use SQUARE BRACKETS [ ]")
print("-"*80)
list_example1 = [1, 2, 3, 4, 5]
list_example2 = ["apple", "banana", "cherry"]
list_example3 = [10, "hello", 3.14, True]
empty_list = []

print(f"Number list: {list_example1}")
print(f"String list: {list_example2}")
print(f"Mixed list: {list_example3}")
print(f"Empty list: {empty_list}")
print(f"Type: {type(list_example1)}")

print("\n TUPLES use PARENTHESES ( )")
print("-"*80)
tuple_example1 = (1, 2, 3, 4, 5)
tuple_example2 = ("apple", "banana", "cherry")
tuple_example3 = (10, "hello", 3.14, True)
empty_tuple = ()

print(f"Number tuple: {tuple_example1}")
print(f"String tuple: {tuple_example2}")
print(f"Mixed tuple: {tuple_example3}")
print(f"Empty tuple: {empty_tuple}")
print(f"Type: {type(tuple_example1)}")

print("\n SPECIAL: Tuple without parentheses!")
print("-"*80)
tuple_without_brackets = 1, 2, 3, 4, 5
print(f"Tuple without (): {tuple_without_brackets}")
print(f"Type: {type(tuple_without_brackets)}")

single_value = 10,
print(f"\nSingle element tuple: {single_value}")
print(f"Type: {type(single_value)}")

print("\n⚠️ IMPORTANT: Single element tuple needs a comma!")
not_a_tuple = (10)  # This is just a number
actual_tuple = (10,)  # This is a tuple

print(f"(10) is type: {type(not_a_tuple)}")
print(f"(10,) is type: {type(actual_tuple)}")


 CONCEPT 1: MUTABILITY - CAN DATA BE CHANGED?

 LISTS are MUTABLE (Can be changed)
--------------------------------------------------------------------------------
Original List: [10, 20, 30, 40, 50]
After changing index 0: [100, 20, 30, 40, 50]
After appending 60: [100, 20, 30, 40, 50, 60]
After removing 30: [100, 20, 40, 50, 60]

 Lists allow: modify, add, remove, sort, reverse

 TUPLES are IMMUTABLE (Cannot be changed)
--------------------------------------------------------------------------------
Original Tuple: (10, 20, 30, 40, 50)

❌ CANNOT do these operations on tuples:
   • immutable_tuple[0] = 100  → ERROR!
   • immutable_tuple.append(60) → ERROR!
   • immutable_tuple.remove(30) → ERROR!
   • immutable_tuple.sort()     → ERROR!

 Tuples allow: access, slice, count, index ONLY

Access element: 10
Slice tuple: (20, 30, 40)
Count occurrences: 1
Find index: 2

 CONCEPT 2: SYNTAX - HOW TO CREATE THEM?

 LISTS use SQUARE BRACKETS [ ]
-----------------------------------------------

In [ ]:
# ============================================================================
# TECHNICAL CONCEPT 3: MEMORY USAGE
# ============================================================================
print("\n" + "="*80)
print(" CONCEPT 3: MEMORY USAGE - WHICH USES LESS SPACE?")
print("="*80)

import sys

same_data_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
same_data_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

list_size = sys.getsizeof(same_data_list)
tuple_size = sys.getsizeof(same_data_tuple)

print(f"\nList [1,2,3...10] uses: {list_size} bytes")
print(f"Tuple (1,2,3...10) uses: {tuple_size} bytes")
print(f"Difference: {list_size - tuple_size} bytes")

print("\n WHY?")
print("-"*80)
print("""
LISTS need extra space for:
✗ Tracking changes (mutations)
✗ Space for adding new elements
✗ Managing dynamic size
→ Uses MORE memory

TUPLES are:
✓ Fixed size (cannot change)
✓ Optimized storage
✓ No mutation tracking needed
→ Uses LESS memory
""")

print(" For large datasets with fixed data, tuples save memory!")

# ============================================================================
# TECHNICAL CONCEPT 4: USE CASES
# ============================================================================
print("\n" + "="*80)
print("📚 CONCEPT 4: USE CASES - WHEN TO USE WHAT?")
print("="*80)

print("\n USE LISTS WHEN:")
print("-"*80)
print("✓ Data needs to CHANGE (add, remove, modify)")
print("✓ Shopping lists, to-do lists, task queues")
print("✓ Collecting user inputs")
print("✓ Storing game scores that update")
print("✓ Managing inventory that changes")

print("\nEXAMPLE 1: Student attendance (changes daily)")
attendance_today = ["Rahul", "Priya", "Arjun"]
print(f"Present: {attendance_today}")
attendance_today.append("Ananya")  # New student joined
print(f"Updated: {attendance_today}")

print("\nEXAMPLE 2: Shopping cart (items added/removed)")
cart = ["Laptop", "Mouse"]
print(f"Cart: {cart}")
cart.append("Keyboard")
cart.append("Monitor")
cart.remove("Mouse")  # Changed mind
print(f"Final Cart: {cart}")

print("\n USE TUPLES WHEN:")
print("-"*80)
print("✓ Data should NEVER change (permanent)")
print("✓ Coordinates (latitude, longitude)")
print("✓ RGB colors (255, 0, 0)")
print("✓ Date of birth, ID numbers")
print("✓ Database records (read-only)")
print("✓ Function return multiple values")


 CONCEPT 3: MEMORY USAGE - WHICH USES LESS SPACE?

List [1,2,3...10] uses: 152 bytes
Tuple (1,2,3...10) uses: 120 bytes
Difference: 32 bytes

 WHY?
--------------------------------------------------------------------------------

LISTS need extra space for:
✗ Tracking changes (mutations)
✗ Space for adding new elements
✗ Managing dynamic size
→ Uses MORE memory

TUPLES are:
✓ Fixed size (cannot change)
✓ Optimized storage
✓ No mutation tracking needed
→ Uses LESS memory

 For large datasets with fixed data, tuples save memory!

📚 CONCEPT 4: USE CASES - WHEN TO USE WHAT?

 USE LISTS WHEN:
--------------------------------------------------------------------------------
✓ Data needs to CHANGE (add, remove, modify)
✓ Shopping lists, to-do lists, task queues
✓ Collecting user inputs
✓ Storing game scores that update
✓ Managing inventory that changes

EXAMPLE 1: Student attendance (changes daily)
Present: ['Rahul', 'Priya', 'Arjun']
Updated: ['Rahul', 'Priya', 'Arjun', 'Ananya']

EXAMPLE 2:

In [ ]:
print("\nEXAMPLE 1: Location coordinates (never change)")
mumbai_coords = (19.0760, 72.8777)
print(f"Mumbai coordinates: {mumbai_coords}")
print(f"Latitude: {mumbai_coords[0]}, Longitude: {mumbai_coords[1]}")

print("\nEXAMPLE 2: RGB color codes (fixed)")
red_color = (255, 0, 0)
green_color = (0, 255, 0)
blue_color = (0, 0, 255)
print(f"Red: {red_color}, Green: {green_color}, Blue: {blue_color}")

print("\nEXAMPLE 3: Student permanent record")
student_record = ("Rahul Sharma", 101, "15-08-2005", "O+")
print(f"Student Record: {student_record}")
print("(Name, Roll, DOB, Blood Group - Cannot be changed)")


EXAMPLE 1: Location coordinates (never change)
Mumbai coordinates: (19.076, 72.8777)
Latitude: 19.076, Longitude: 72.8777

EXAMPLE 2: RGB color codes (fixed)
Red: (255, 0, 0), Green: (0, 255, 0), Blue: (0, 0, 255)

EXAMPLE 3: Student permanent record
Student Record: ('Rahul Sharma', 101, '15-08-2005', 'O+')
(Name, Roll, DOB, Blood Group - Cannot be changed)


In [ ]:
# ============================================================================
# TECHNICAL CONCEPT 5: METHODS COMPARISON
# ============================================================================
print("\n" + "="*80)
print("📚 CONCEPT 5: AVAILABLE METHODS")
print("="*80)

print("\n📋 LIST METHODS (11 methods)")
print("-"*80)

demo_list = [3, 1, 4, 1, 5, 9, 2, 6]
print(f"Demo List: {demo_list}")

print("\n1️⃣ append() - Add element at end")
demo_list.append(7)
print(f"   After append(7): {demo_list}")

print("\n2️⃣ insert() - Add element at specific position")
demo_list.insert(0, 0)
print(f"   After insert(0, 0): {demo_list}")

print("\n3️⃣ extend() - Add multiple elements")
demo_list.extend([8, 9])
print(f"   After extend([8,9]): {demo_list}")

print("\n4️⃣ remove() - Remove first occurrence")
demo_list.remove(1)
print(f"   After remove(1): {demo_list}")

print("\n5️⃣ pop() - Remove and return last element")
removed = demo_list.pop()
print(f"   After pop(): {demo_list}, Removed: {removed}")

print("\n6️⃣ clear() - Remove all elements")
temp_list = [1, 2, 3]
print(f"   Before clear(): {temp_list}")
temp_list.clear()
print(f"   After clear(): {temp_list}")


📚 CONCEPT 5: AVAILABLE METHODS

📋 LIST METHODS (11 methods)
--------------------------------------------------------------------------------
Demo List: [3, 1, 4, 1, 5, 9, 2, 6]

1️⃣ append() - Add element at end
   After append(7): [3, 1, 4, 1, 5, 9, 2, 6, 7]

2️⃣ insert() - Add element at specific position
   After insert(0, 0): [0, 3, 1, 4, 1, 5, 9, 2, 6, 7]

3️⃣ extend() - Add multiple elements
   After extend([8,9]): [0, 3, 1, 4, 1, 5, 9, 2, 6, 7, 8, 9]

4️⃣ remove() - Remove first occurrence
   After remove(1): [0, 3, 4, 1, 5, 9, 2, 6, 7, 8, 9]

5️⃣ pop() - Remove and return last element
   After pop(): [0, 3, 4, 1, 5, 9, 2, 6, 7, 8], Removed: 9

6️⃣ clear() - Remove all elements
   Before clear(): [1, 2, 3]
   After clear(): []


In [ ]:
demo_list = [3, 1, 4, 1, 5, 9, 2, 6]  # Reset

print("\n7️⃣ index() - Find position of element")
position = demo_list.index(5)
print(f"   Position of 5: {position}")

print("\n8️⃣ count() - Count occurrences")
count_1 = demo_list.count(1)
print(f"   Count of 1: {count_1}")

print("\n9️⃣ sort() - Sort in ascending order")
demo_list.sort()
print(f"   After sort(): {demo_list}")

print("\n🔟 reverse() - Reverse order")
demo_list.reverse()
print(f"   After reverse(): {demo_list}")

print("\n1️⃣1️⃣ copy() - Create a copy")
copied = demo_list.copy()
print(f"   Copied list: {copied}")


7️⃣ index() - Find position of element
   Position of 5: 4

8️⃣ count() - Count occurrences
   Count of 1: 2

9️⃣ sort() - Sort in ascending order
   After sort(): [1, 1, 2, 3, 4, 5, 6, 9]

🔟 reverse() - Reverse order
   After reverse(): [9, 6, 5, 4, 3, 2, 1, 1]

1️⃣1️⃣ copy() - Create a copy
   Copied list: [9, 6, 5, 4, 3, 2, 1, 1]


In [ ]:
print("\n📋 TUPLE METHODS (Only 2 methods!)")
print("-"*80)

demo_tuple = (3, 1, 4, 1, 5, 9, 2, 6, 1)
print(f"Demo Tuple: {demo_tuple}")

print("\n1️⃣ index() - Find position of element")
position = demo_tuple.index(5)
print(f"   Position of 5: {position}")

print("\n2️⃣ count() - Count occurrences")
count_1 = demo_tuple.count(1)
print(f"   Count of 1: {count_1}")

print("\n⚠️ WHY ONLY 2 METHODS?")
print("   Because tuples are IMMUTABLE - cannot add, remove, or modify!")


📋 TUPLE METHODS (Only 2 methods!)
--------------------------------------------------------------------------------
Demo Tuple: (3, 1, 4, 1, 5, 9, 2, 6, 1)

1️⃣ index() - Find position of element
   Position of 5: 4

2️⃣ count() - Count occurrences
   Count of 1: 3

⚠️ WHY ONLY 2 METHODS?
   Because tuples are IMMUTABLE - cannot add, remove, or modify!


In [ ]:
# ============================================================================
# COMPARISON TABLE
# ============================================================================
print("\n" + "="*80)
print(" QUICK COMPARISON TABLE")
print("="*80)

comparison = """
╔═══════════════════╦═══════════════════════╦═══════════════════════╗
║    FEATURE        ║        LIST           ║       TUPLE           ║
╠═══════════════════╬═══════════════════════╬═══════════════════════╣
║ Syntax            ║ [ ]                   ║ ( ) or just comma     ║
║ Mutable           ║ Yes (can change)      ║ No (cannot change)    ║
║ Add items         ║ ✓ Yes                 ║ ✗ No                  ║
║ Remove items      ║ ✓ Yes                 ║ ✗ No                  ║
║ Modify items      ║ ✓ Yes                 ║ ✗ No                  ║
║ Memory usage      ║ More                  ║ Less                  ║
║ Speed             ║ Slower                ║ Faster                ║
║ Methods           ║ 11 methods            ║ 2 methods             ║
║ Use case          ║ Dynamic data          ║ Fixed data            ║
║ Example           ║ Shopping list         ║ Date of birth         ║
╚═══════════════════╩═══════════════════════╩═══════════════════════╝
"""
print(comparison)


 QUICK COMPARISON TABLE

╔═══════════════════╦═══════════════════════╦═══════════════════════╗
║    FEATURE        ║        LIST           ║       TUPLE           ║
╠═══════════════════╬═══════════════════════╬═══════════════════════╣
║ Syntax            ║ [ ]                   ║ ( ) or just comma     ║
║ Mutable           ║ Yes (can change)      ║ No (cannot change)    ║
║ Add items         ║ ✓ Yes                 ║ ✗ No                  ║
║ Remove items      ║ ✓ Yes                 ║ ✗ No                  ║
║ Modify items      ║ ✓ Yes                 ║ ✗ No                  ║
║ Memory usage      ║ More                  ║ Less                  ║
║ Speed             ║ Slower                ║ Faster                ║
║ Methods           ║ 11 methods            ║ 2 methods             ║
║ Use case          ║ Dynamic data          ║ Fixed data            ║
║ Example           ║ Shopping list         ║ Date of birth         ║
╚═══════════════════╩═══════════════════════╩═══════════════════

In [ ]:
# ============================================================================
# MINI PROJECT: STUDENT MANAGEMENT SYSTEM
# ============================================================================
print("\n" + "="*80)
print("      MINI PROJECT: SMART STUDENT MANAGEMENT")
print("="*80)

print("\n USING LISTS AND TUPLES TOGETHER")
print("-"*80)

# Fixed student information (TUPLE - cannot change)
student1 = ("Rahul Sharma", 101, "15-08-2005")
student2 = ("Priya Patel", 102, "22-05-2005")
student3 = ("Arjun Kumar", 103, "10-11-2005")

print("PERMANENT STUDENT RECORDS (Tuples):")
print(f"Student 1: {student1}")
print(f"Student 2: {student2}")
print(f"Student 3: {student3}")

# Dynamic marks (LIST - changes every exam)
rahul_marks = [85, 90, 88]
priya_marks = [92, 88, 95]
arjun_marks = [78, 82, 80]

print("\nEXAM MARKS (Lists - change with each exam):")
print(f"Rahul's marks: {rahul_marks}")
print(f"Priya's marks: {priya_marks}")
print(f"Arjun's marks: {arjun_marks}")

# Add new exam marks
print("\n New exam completed! Adding marks...")
rahul_marks.append(87)
priya_marks.append(90)
arjun_marks.append(85)

print(f"Rahul's updated marks: {rahul_marks}")
print(f"Priya's updated marks: {priya_marks}")
print(f"Arjun's updated marks: {arjun_marks}")

# Calculate averages
rahul_avg = sum(rahul_marks) / len(rahul_marks)
priya_avg = sum(priya_marks) / len(priya_marks)
arjun_avg = sum(arjun_marks) / len(arjun_marks)

print("\n PERFORMANCE ANALYSIS:")
print(f"{student1[0]} (Roll {student1[1]}): Average = {rahul_avg:.2f}%")
print(f"{student2[0]} (Roll {student2[1]}): Average = {priya_avg:.2f}%")
print(f"{student3[0]} (Roll {student3[1]}): Average = {arjun_avg:.2f}%")

# Find topper using if-elif-else
print("\n FINDING TOPPER...")
if rahul_avg > priya_avg and rahul_avg > arjun_avg:
    topper = student1[0]
    topper_avg = rahul_avg
elif priya_avg > rahul_avg and priya_avg > arjun_avg:
    topper = student2[0]
    topper_avg = priya_avg
else:
    topper = student3[0]
    topper_avg = arjun_avg

print(f" TOPPER: {topper} with {topper_avg:.2f}% average!")

# ============================================================================
# KEY TAKEAWAYS
# ============================================================================
print("\n" + "="*80)
print(" KEY TAKEAWAYS")
print("="*80)

takeaways = """
1.  LISTS = Mutable (changeable)
   → Use for: shopping lists, tasks, scores, anything that updates

2.  TUPLES = Immutable (fixed)
   → Use for: coordinates, IDs, dates, permanent data

3.  LISTS have many methods (append, remove, sort, etc.)

4.  TUPLES have only 2 methods (count, index)

5.  TUPLES use less memory than lists

6. ⚡ TUPLES are faster than lists

7.  CHOOSE based on whether data will change or stay fixed

REMEMBER:
□ Shopping list → LIST (changes)
■ Birth date → TUPLE (permanent)
"""
print(takeaways)

print("\n" + "="*80)
print("     END OF DAY 8 - LISTS vs TUPLES MASTERY")
print("="*80)


      MINI PROJECT: SMART STUDENT MANAGEMENT

 USING LISTS AND TUPLES TOGETHER
--------------------------------------------------------------------------------
PERMANENT STUDENT RECORDS (Tuples):
Student 1: ('Rahul Sharma', 101, '15-08-2005')
Student 2: ('Priya Patel', 102, '22-05-2005')
Student 3: ('Arjun Kumar', 103, '10-11-2005')

EXAM MARKS (Lists - change with each exam):
Rahul's marks: [85, 90, 88]
Priya's marks: [92, 88, 95]
Arjun's marks: [78, 82, 80]

 New exam completed! Adding marks...
Rahul's updated marks: [85, 90, 88, 87]
Priya's updated marks: [92, 88, 95, 90]
Arjun's updated marks: [78, 82, 80, 85]

 PERFORMANCE ANALYSIS:
Rahul Sharma (Roll 101): Average = 87.50%
Priya Patel (Roll 102): Average = 91.25%
Arjun Kumar (Roll 103): Average = 81.25%

 FINDING TOPPER...
 TOPPER: Priya Patel with 91.25% average!

 KEY TAKEAWAYS

1.  LISTS = Mutable (changeable)
   → Use for: shopping lists, tasks, scores, anything that updates
   
2.  TUPLES = Immutable (fixed)
   → Use for: c

DAY 8: LISTS vs TUPLES - INTERVIEW QUESTIONS & ANSWERS
=======================================================
10 Most Common Interview Questions with Detailed Explanations

In [ ]:
print("="*80)
print("     LISTS vs TUPLES - TOP 10 INTERVIEW QUESTIONS")
print("="*80)

     LISTS vs TUPLES - TOP 10 INTERVIEW QUESTIONS


In [ ]:
# ============================================================================
# QUESTION 1: What is the main difference between Lists and Tuples?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 1: What is the MAIN difference between Lists and Tuples?")
print("="*80)

print("\n ANSWER:")
print("-"*80)
print("""
The MAIN difference is MUTABILITY:

 LISTS are MUTABLE:
   - Can be changed after creation
   - Can add, remove, modify elements
   - Example: shopping_list.append("Milk")

 TUPLES are IMMUTABLE:
   - Cannot be changed after creation
   - Cannot add, remove, or modify elements
   - Example: birth_date = (15, 8, 2005) [permanent]
""")

# Demonstration
print("DEMONSTRATION:")
print("-"*80)

# List - Mutable
my_list = [1, 2, 3]
print(f"Original List: {my_list}")
my_list[0] = 100
my_list.append(4)
print(f"Modified List: {my_list} ✓ ALLOWED")

# Tuple - Immutable
my_tuple = (1, 2, 3)
print(f"\nOriginal Tuple: {my_tuple}")
print("Trying: my_tuple[0] = 100")
print("Result: ✗ TypeError: 'tuple' object does not support item assignment")

print("\n KEY POINT: Lists change, Tuples don't!")


 QUESTION 1: What is the MAIN difference between Lists and Tuples?

 ANSWER:
--------------------------------------------------------------------------------

The MAIN difference is MUTABILITY:

 LISTS are MUTABLE:
   - Can be changed after creation
   - Can add, remove, modify elements
   - Example: shopping_list.append("Milk")

 TUPLES are IMMUTABLE:
   - Cannot be changed after creation
   - Cannot add, remove, or modify elements
   - Example: birth_date = (15, 8, 2005) [permanent]

DEMONSTRATION:
--------------------------------------------------------------------------------
Original List: [1, 2, 3]
Modified List: [100, 2, 3, 4] ✓ ALLOWED

Original Tuple: (1, 2, 3)
Trying: my_tuple[0] = 100
Result: ✗ TypeError: 'tuple' object does not support item assignment

 KEY POINT: Lists change, Tuples don't!


In [ ]:
# ============================================================================
# QUESTION 2: How do you create a tuple with only one element?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 2: How do you create a tuple with only ONE element?")
print("="*80)

print("\n ANSWER:")
print("-"*80)
print("""
To create a single-element tuple, you MUST add a comma after the element.
Without comma, Python treats it as a regular value in parentheses.
""")

# Demonstration
print("DEMONSTRATION:")
print("-"*80)

# Wrong way - NOT a tuple
not_a_tuple = (10)
print(f"not_a_tuple = (10)")
print(f"Type: {type(not_a_tuple)} ✗ This is an INTEGER, not a tuple!")

# Correct way - IS a tuple
correct_tuple = (10,)
print(f"\ncorrect_tuple = (10,)")
print(f"Type: {type(correct_tuple)} ✓ This is a TUPLE!")

# Without parentheses also works
another_tuple = 10,
print(f"\nanother_tuple = 10,")
print(f"Type: {type(another_tuple)} ✓ This is also a TUPLE!")

print("\n KEY POINT: Single element tuple needs a trailing comma!")



 QUESTION 2: How do you create a tuple with only ONE element?

 ANSWER:
--------------------------------------------------------------------------------

To create a single-element tuple, you MUST add a comma after the element.
Without comma, Python treats it as a regular value in parentheses.

DEMONSTRATION:
--------------------------------------------------------------------------------
not_a_tuple = (10)
Type: <class 'int'> ✗ This is an INTEGER, not a tuple!

correct_tuple = (10,)
Type: <class 'tuple'> ✓ This is a TUPLE!

another_tuple = 10,
Type: <class 'tuple'> ✓ This is also a TUPLE!

 KEY POINT: Single element tuple needs a trailing comma!


In [ ]:
# ============================================================================
# QUESTION 3: Which is faster - List or Tuple? Why?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 3: Which is FASTER - List or Tuple? Why?")
print("="*80)

print("\n ANSWER:")
print("-"*80)
print("""
TUPLES are FASTER than Lists because:

1. Fixed Size: Tuples have fixed size, no need to allocate extra space
2. Immutable: No overhead for tracking changes
3. Optimized: Python optimizes tuple storage in memory
4. Simple: Less operations = faster access

LISTS are SLOWER because:
1. Dynamic Size: Need extra space for potential additions
2. Mutable: System tracks possible changes
3. Overhead: More memory management needed
""")

# Demonstration with timing
import time

print("DEMONSTRATION (Creating 1 million times):")
print("-"*80)

# Timing List creation
start_time = time.time()
my_list = [1, 2, 3, 4, 5]
end_time = time.time()
list_time = end_time - start_time

# Timing Tuple creation
start_time = time.time()
my_tuple = (1, 2, 3, 4, 5)
end_time = time.time()
tuple_time = end_time - start_time

print(f"List creation time: {list_time:.10f} seconds")
print(f"Tuple creation time: {tuple_time:.10f} seconds")
print(f"\n✓ Tuples are faster for access and iteration!")

print("\n KEY POINT: Use tuples for better performance with fixed data!")


 QUESTION 3: Which is FASTER - List or Tuple? Why?

 ANSWER:
--------------------------------------------------------------------------------

TUPLES are FASTER than Lists because:

1. Fixed Size: Tuples have fixed size, no need to allocate extra space
2. Immutable: No overhead for tracking changes
3. Optimized: Python optimizes tuple storage in memory
4. Simple: Less operations = faster access

LISTS are SLOWER because:
1. Dynamic Size: Need extra space for potential additions
2. Mutable: System tracks possible changes
3. Overhead: More memory management needed

DEMONSTRATION (Creating 1 million times):
--------------------------------------------------------------------------------
List creation time: 0.0000698566 seconds
Tuple creation time: 0.0000591278 seconds

✓ Tuples are faster for access and iteration!

 KEY POINT: Use tuples for better performance with fixed data!


In [ ]:
# ============================================================================
# QUESTION 4: Can you change a tuple? If yes, how?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 4: Can you CHANGE a tuple? If yes, how?")
print("="*80)

print("\n ANSWER:")
print("-"*80)
print("""
NO, you cannot directly change a tuple (it's immutable).

HOWEVER, you can:
1. Convert to list, modify, convert back to tuple
2. Create a new tuple with desired changes
3. If tuple contains mutable objects (like lists), those can be modified
""")

# Demonstration
print("DEMONSTRATION:")
print("-"*80)

# Method 1: Convert to list
original_tuple = (1, 2, 3, 4, 5)
print(f"Original Tuple: {original_tuple}")

temp_list = list(original_tuple)
temp_list[0] = 100
new_tuple = tuple(temp_list)
print(f"New Tuple (via list): {new_tuple}")

# Method 2: Create new tuple
new_tuple2 = (100,) + original_tuple[1:]
print(f"New Tuple (concatenation): {new_tuple2}")

# Method 3: Tuple with mutable elements
tuple_with_list = (1, 2, [3, 4, 5])
print(f"\nTuple with list inside: {tuple_with_list}")
tuple_with_list[2][0] = 300  # Can modify the list inside
print(f"After modifying inner list: {tuple_with_list}")

print("\n KEY POINT: Tuple itself can't change, but workarounds exist!")


 QUESTION 4: Can you CHANGE a tuple? If yes, how?

 ANSWER:
--------------------------------------------------------------------------------

NO, you cannot directly change a tuple (it's immutable).

HOWEVER, you can:
1. Convert to list, modify, convert back to tuple
2. Create a new tuple with desired changes
3. If tuple contains mutable objects (like lists), those can be modified

DEMONSTRATION:
--------------------------------------------------------------------------------
Original Tuple: (1, 2, 3, 4, 5)
New Tuple (via list): (100, 2, 3, 4, 5)
New Tuple (concatenation): (100, 2, 3, 4, 5)

Tuple with list inside: (1, 2, [3, 4, 5])
After modifying inner list: (1, 2, [300, 4, 5])

 KEY POINT: Tuple itself can't change, but workarounds exist!


In [ ]:
# ============================================================================
# QUESTION 5: When should you use List vs Tuple?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 5: WHEN should you use List vs Tuple?")
print("="*80)

print("\n ANSWER:")
print("-"*80)
print("""
USE LISTS when:
✓ Data needs to change (add/remove/modify)
✓ Building dynamic collections
✓ User input that grows/shrinks
✓ Temporary data processing

USE TUPLES when:
✓ Data should never change
✓ Protecting data from modification
✓ Dictionary keys (lists can't be keys)
✓ Function returns multiple values
✓ Performance is critical
✓ Coordinates, dates, IDs
""")

# Demonstration
print("DEMONSTRATION:")
print("-"*80)

print("\n LIST EXAMPLE - Shopping Cart (changes):")
shopping_cart = ["Laptop", "Mouse"]
print(f"Initial Cart: {shopping_cart}")
shopping_cart.append("Keyboard")
shopping_cart.remove("Mouse")
print(f"Updated Cart: {shopping_cart}")

print("\n TUPLE EXAMPLE - GPS Coordinates (fixed):")
mumbai_location = (19.0760, 72.8777)
delhi_location = (28.7041, 77.1025)
print(f"Mumbai: {mumbai_location}")
print(f"Delhi: {delhi_location}")
print("(Coordinates never change!)")

print("\n TUPLE as Dictionary Key:")
locations = {}
locations[mumbai_location] = "Mumbai"
locations[delhi_location] = "Delhi"
print(f"Location Dict: {locations}")
print("✓ Tuples can be dict keys, lists cannot!")

print("\n KEY POINT: Lists for change, Tuples for permanence!")



 QUESTION 5: WHEN should you use List vs Tuple?

 ANSWER:
--------------------------------------------------------------------------------

USE LISTS when:
✓ Data needs to change (add/remove/modify)
✓ Building dynamic collections
✓ User input that grows/shrinks
✓ Temporary data processing

USE TUPLES when:
✓ Data should never change
✓ Protecting data from modification
✓ Dictionary keys (lists can't be keys)
✓ Function returns multiple values
✓ Performance is critical
✓ Coordinates, dates, IDs

DEMONSTRATION:
--------------------------------------------------------------------------------

 LIST EXAMPLE - Shopping Cart (changes):
Initial Cart: ['Laptop', 'Mouse']
Updated Cart: ['Laptop', 'Keyboard']

 TUPLE EXAMPLE - GPS Coordinates (fixed):
Mumbai: (19.076, 72.8777)
Delhi: (28.7041, 77.1025)
(Coordinates never change!)

 TUPLE as Dictionary Key:
Location Dict: {(19.076, 72.8777): 'Mumbai', (28.7041, 77.1025): 'Delhi'}
✓ Tuples can be dict keys, lists cannot!

 KEY POINT: Lists for cha

In [ ]:
# ============================================================================
# QUESTION 6: What methods are available in List and Tuple?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 6: What METHODS are available in List and Tuple?")
print("="*80)

print("\n ANSWER:")
print("-"*80)

print(" LIST METHODS (11 total):")
print("   Modifying: append(), insert(), extend(), remove(), pop(), clear()")
print("   Organizing: sort(), reverse()")
print("   Information: index(), count()")
print("   Copying: copy()")

print("\n TUPLE METHODS (2 total):")
print("   Information only: index(), count()")
print("   (No modifying methods because tuples are immutable)")

# Demonstration
print("\nDEMONSTRATION:")
print("-"*80)

demo_list = [1, 2, 3, 2, 4]
demo_tuple = (1, 2, 3, 2, 4)

print(f"List: {demo_list}")
print(f"List methods available: {[m for m in dir(demo_list) if not m.startswith('_')]}")

print(f"\nTuple: {demo_tuple}")
print(f"Tuple methods available: {[m for m in dir(demo_tuple) if not m.startswith('_')]}")

# Common methods
print(f"\nCommon: count(2) - List: {demo_list.count(2)}, Tuple: {demo_tuple.count(2)}")
print(f"Common: index(3) - List: {demo_list.index(3)}, Tuple: {demo_tuple.index(3)}")

print("\n KEY POINT: Lists have 11 methods, Tuples have only 2!")


 QUESTION 6: What METHODS are available in List and Tuple?

 ANSWER:
--------------------------------------------------------------------------------
 LIST METHODS (11 total):
   Modifying: append(), insert(), extend(), remove(), pop(), clear()
   Organizing: sort(), reverse()
   Information: index(), count()
   Copying: copy()

 TUPLE METHODS (2 total):
   Information only: index(), count()
   (No modifying methods because tuples are immutable)

DEMONSTRATION:
--------------------------------------------------------------------------------
List: [1, 2, 3, 2, 4]
List methods available: ['append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']

Tuple: (1, 2, 3, 2, 4)
Tuple methods available: ['count', 'index']

Common: count(2) - List: 2, Tuple: 2
Common: index(3) - List: 2, Tuple: 2

 KEY POINT: Lists have 11 methods, Tuples have only 2!


In [ ]:
# ============================================================================
# QUESTION 7: Which uses more memory - List or Tuple?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 7: Which uses MORE MEMORY - List or Tuple?")
print("="*80)

print("\n ANSWER:")
print("-"*80)
print("""
LISTS use MORE memory than Tuples because:

1. Lists need extra space for dynamic operations
2. Lists store additional information for mutability
3. Lists allocate buffer space for future additions
4. Tuples are optimized for fixed size

Memory overhead: List > Tuple (typically 10-20% more)
""")

# Demonstration
import sys

print("DEMONSTRATION:")
print("-"*80)

same_data_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
same_data_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

list_size = sys.getsizeof(same_data_list)
tuple_size = sys.getsizeof(same_data_tuple)
difference = list_size - tuple_size

print(f"List [1-10]:  {list_size} bytes")
print(f"Tuple (1-10): {tuple_size} bytes")
print(f"Difference:   {difference} bytes ({(difference/tuple_size)*100:.1f}% more)")

# Larger example
large_list = list(range(100))
large_tuple = tuple(range(100))

print(f"\nList [1-100]:  {sys.getsizeof(large_list)} bytes")
print(f"Tuple (1-100): {sys.getsizeof(large_tuple)} bytes")

print("\n KEY POINT: For large datasets, tuples save significant memory!")



 QUESTION 7: Which uses MORE MEMORY - List or Tuple?

 ANSWER:
--------------------------------------------------------------------------------

LISTS use MORE memory than Tuples because:

1. Lists need extra space for dynamic operations
2. Lists store additional information for mutability
3. Lists allocate buffer space for future additions
4. Tuples are optimized for fixed size

Memory overhead: List > Tuple (typically 10-20% more)

DEMONSTRATION:
--------------------------------------------------------------------------------
List [1-10]:  152 bytes
Tuple (1-10): 120 bytes
Difference:   32 bytes (26.7% more)

List [1-100]:  856 bytes
Tuple (1-100): 840 bytes

 KEY POINT: For large datasets, tuples save significant memory!


In [ ]:
# ============================================================================
# QUESTION 8: Can a tuple contain a list? What happens then?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 8: Can a tuple CONTAIN a list? What happens then?")
print("="*80)

print("\n ANSWER:")
print("-"*80)
print("""
YES, a tuple can contain a list!

KEY CONCEPT:
- The TUPLE structure itself is immutable (can't add/remove elements)
- But if tuple contains a LIST, that list is still MUTABLE
- You cannot replace the list, but you can modify its contents

Think of it as: The container (tuple) is locked, but items inside (list)
can still be changed.
""")

# Demonstration
print("DEMONSTRATION:")
print("-"*80)

student_data = ("Rahul", 101, [85, 90, 88])
print(f"Student Data: {student_data}")
print(f"Name: {student_data[0]}")
print(f"Roll: {student_data[1]}")
print(f"Marks: {student_data[2]}")

print("\n Cannot do: student_data[0] = 'New Name' (tuple is immutable)")
print(" Cannot do: student_data[2] = [100, 100, 100] (can't replace list)")

print("\n✓ Can do: student_data[2].append(92) (modify list inside)")
student_data[2].append(92)
print(f"After appending mark: {student_data}")

print("\n✓ Can do: student_data[2][0] = 95 (change list element)")
student_data[2][0] = 95
print(f"After modifying first mark: {student_data}")

print("\n KEY POINT: Tuple structure fixed, but mutable contents can change!")


 QUESTION 8: Can a tuple CONTAIN a list? What happens then?

 ANSWER:
--------------------------------------------------------------------------------

YES, a tuple can contain a list!

KEY CONCEPT:
- The TUPLE structure itself is immutable (can't add/remove elements)
- But if tuple contains a LIST, that list is still MUTABLE
- You cannot replace the list, but you can modify its contents

Think of it as: The container (tuple) is locked, but items inside (list) 
can still be changed.

DEMONSTRATION:
--------------------------------------------------------------------------------
Student Data: ('Rahul', 101, [85, 90, 88])
Name: Rahul
Roll: 101
Marks: [85, 90, 88]

 Cannot do: student_data[0] = 'New Name' (tuple is immutable)
 Cannot do: student_data[2] = [100, 100, 100] (can't replace list)

✓ Can do: student_data[2].append(92) (modify list inside)
After appending mark: ('Rahul', 101, [85, 90, 88, 92])

✓ Can do: student_data[2][0] = 95 (change list element)
After modifying first mark: 

In [ ]:
# ============================================================================
# QUESTION 9: How do you create an empty List and empty Tuple?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 9: How do you create EMPTY List and empty Tuple?")
print("="*80)

print("\n ANSWER:")
print("-"*80)

# Empty List
empty_list_1 = []
empty_list_2 = list()

print("EMPTY LIST:")
print(f"Method 1: empty_list = []")
print(f"   Result: {empty_list_1}, Type: {type(empty_list_1)}")
print(f"Method 2: empty_list = list()")
print(f"   Result: {empty_list_2}, Type: {type(empty_list_2)}")

# Empty Tuple
empty_tuple_1 = ()
empty_tuple_2 = tuple()

print("\nEMPTY TUPLE:")
print(f"Method 1: empty_tuple = ()")
print(f"   Result: {empty_tuple_1}, Type: {type(empty_tuple_1)}")
print(f"Method 2: empty_tuple = tuple()")
print(f"   Result: {empty_tuple_2}, Type: {type(empty_tuple_2)}")

print("\nUSAGE:")
print("-"*80)
print("Empty list for collecting data:")
marks = []
marks.append(85)
marks.append(90)
print(f"Collected marks: {marks}")

print("\n KEY POINT: [] for list, () for tuple, or use list() and tuple()")


 QUESTION 9: How do you create EMPTY List and empty Tuple?

 ANSWER:
--------------------------------------------------------------------------------
EMPTY LIST:
Method 1: empty_list = []
   Result: [], Type: <class 'list'>
Method 2: empty_list = list()
   Result: [], Type: <class 'list'>

EMPTY TUPLE:
Method 1: empty_tuple = ()
   Result: (), Type: <class 'tuple'>
Method 2: empty_tuple = tuple()
   Result: (), Type: <class 'tuple'>

USAGE:
--------------------------------------------------------------------------------
Empty list for collecting data:
Collected marks: [85, 90]

 KEY POINT: [] for list, () for tuple, or use list() and tuple()


In [ ]:
# ============================================================================
# QUESTION 10: What is tuple packing and unpacking?
# ============================================================================
print("\n" + "="*80)
print(" QUESTION 10: What is TUPLE PACKING and UNPACKING?")
print("="*80)

print("\n ANSWER:")
print("-"*80)
print("""
TUPLE PACKING:
- Automatically creating a tuple by assigning multiple values
- Example: coordinates = 10, 20, 30

TUPLE UNPACKING:
- Extracting tuple values into separate variables
- Example: x, y, z = coordinates

This is a powerful Python feature for clean code!
""")

# Demonstration
print("DEMONSTRATION:")
print("-"*80)

# Tuple Packing
print("1️⃣ TUPLE PACKING:")
coordinates = 19.0760, 72.8777, 10  # No parentheses needed!
print(f"coordinates = 19.0760, 72.8777, 10")
print(f"Result: {coordinates}")
print(f"Type: {type(coordinates)}")

student = "Rahul", 101, 85.5
print(f"\nstudent = 'Rahul', 101, 85.5")
print(f"Result: {student}")

# Tuple Unpacking
print("\n2️⃣ TUPLE UNPACKING:")
latitude, longitude, altitude = coordinates
print(f"latitude, longitude, altitude = coordinates")
print(f"latitude = {latitude}")
print(f"longitude = {longitude}")
print(f"altitude = {altitude}")

name, roll, percentage = student
print(f"\nname, roll, percentage = student")
print(f"name = {name}")
print(f"roll = {roll}")
print(f"percentage = {percentage}")

# Practical use - Swapping
print("\n3️⃣ PRACTICAL USE - SWAPPING:")
a = 10
b = 20
print(f"Before: a = {a}, b = {b}")
a, b = b, a  # Swap using tuple unpacking!
print(f"After:  a = {a}, b = {b}")

# Function returning multiple values
print("\n4️⃣ FUNCTION RETURNS (Advanced preview):")
def get_student_info():
    return "Priya", 102, 92.5  # Returns tuple

name, roll, marks = get_student_info()  # Unpacking
print(f"Student: {name}, Roll: {roll}, Marks: {marks}")

print("\n💡 KEY POINT: Packing creates tuple, unpacking extracts values!")


 QUESTION 10: What is TUPLE PACKING and UNPACKING?

 ANSWER:
--------------------------------------------------------------------------------

TUPLE PACKING:
- Automatically creating a tuple by assigning multiple values
- Example: coordinates = 10, 20, 30

TUPLE UNPACKING:
- Extracting tuple values into separate variables
- Example: x, y, z = coordinates

This is a powerful Python feature for clean code!

DEMONSTRATION:
--------------------------------------------------------------------------------
1️⃣ TUPLE PACKING:
coordinates = 19.0760, 72.8777, 10
Result: (19.076, 72.8777, 10)
Type: <class 'tuple'>

student = 'Rahul', 101, 85.5
Result: ('Rahul', 101, 85.5)

2️⃣ TUPLE UNPACKING:
latitude, longitude, altitude = coordinates
latitude = 19.076
longitude = 72.8777
altitude = 10

name, roll, percentage = student
name = Rahul
roll = 101
percentage = 85.5

3️⃣ PRACTICAL USE - SWAPPING:
Before: a = 10, b = 20
After:  a = 20, b = 10

4️⃣ FUNCTION RETURNS (Advanced preview):
Student: Priya, 

In [ ]:
# ============================================================================
# SUMMARY
# ============================================================================
print("\n" + "="*80)
print(" INTERVIEW QUESTIONS SUMMARY")
print("="*80)

summary = """
Q1: Main difference? → MUTABILITY (List mutable, Tuple immutable)
Q2: Single element tuple? → Add comma: (10,)
Q3: Which is faster? → TUPLE (optimized, fixed size)
Q4: Change tuple? → No direct way, convert to list or create new
Q5: When to use? → List for changes, Tuple for fixed data
Q6: Available methods? → List: 11, Tuple: 2 (count, index)
Q7: More memory? → LIST uses more (dynamic overhead)
Q8: Tuple with list? → Yes, list inside is still mutable
Q9: Create empty? → List: [], Tuple: ()
Q10: Packing/Unpacking? → Packing creates, unpacking extracts

 GOLDEN RULES:
   ✓ List = Mutable = Changeable = Dynamic = []
   ✓ Tuple = Immutable = Fixed = Fast = ()
   ✓ Choose based on whether data will change!
"""
print(summary)

print("\n" + "="*80)
print("     END OF INTERVIEW QUESTIONS")
print("="*80)

print("\n🎯 PRO TIPS FOR INTERVIEWS:")
print("-"*80)
print("""
1. Always mention MUTABILITY first (most important difference)
2. Give real-world examples (shopping list vs birth date)
3. Mention performance (tuples are faster)
4. Mention memory (tuples use less)
5. Show you know both syntax: [] and ()
6. Explain when to use which (this shows understanding)
7. Be ready to write code examples on the spot!

Good luck with your interviews!
""")
print("="*80)


 INTERVIEW QUESTIONS SUMMARY

Q1: Main difference? → MUTABILITY (List mutable, Tuple immutable)
Q2: Single element tuple? → Add comma: (10,)
Q3: Which is faster? → TUPLE (optimized, fixed size)
Q4: Change tuple? → No direct way, convert to list or create new
Q5: When to use? → List for changes, Tuple for fixed data
Q6: Available methods? → List: 11, Tuple: 2 (count, index)
Q7: More memory? → LIST uses more (dynamic overhead)
Q8: Tuple with list? → Yes, list inside is still mutable
Q9: Create empty? → List: [], Tuple: ()
Q10: Packing/Unpacking? → Packing creates, unpacking extracts

 GOLDEN RULES:
   ✓ List = Mutable = Changeable = Dynamic = []
   ✓ Tuple = Immutable = Fixed = Fast = ()
   ✓ Choose based on whether data will change!


     END OF INTERVIEW QUESTIONS

🎯 PRO TIPS FOR INTERVIEWS:
--------------------------------------------------------------------------------

1. Always mention MUTABILITY first (most important difference)
2. Give real-world examples (shopping list vs birt

# Day 9: Looping Logic – Mastering Iteration


What is a Loop?

Real-World Scenario:

How Humans vs Machines Work
How a HUMAN counts 1 to 5:

I manually say: 1, 2, 3, 4, 5
It takes effort and time
If asked to count to 1000, it would be exhausting!

How a MACHINE counts 1 to 5:

Give it one instruction: "Count from 1 to 5"
It repeats the counting automatically
It can count to 1 million without getting tired!

That's what loops do - they repeat a block of code automatically without writing it 100 times!

### TYPE 1: FOR LOOPS

Real-World Scenario: Checking Student Marks

Human Teacher:

Goes through the mark list one by one
Checks each student's mark
Does the same action for each student

Machine (Python):

Gets told: "Check every mark in this list"
Does the same thing automatically for each mark


----------



**ULTRA BASIC EXAMPLE 1: Printing "Hello" 5 Time**

Without a loop (BAD - Repetitive):

In [ ]:
print("Hello")
print("Hello")
print("Hello")
print("Hello")
print("Hello")

Hello
Hello
Hello
Hello
Hello


With a loop (GOOD - Smart!):

In [ ]:
for i in range(5):
    print("Hello")

Hello
Hello
Hello
Hello
Hello


In [ ]:
print("hello")

hello


In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


#### EXAMPLE 1: Printing "Hello" 100 Times

In [ ]:
# Print "Hello" 100 times
for i in range(100):
    print("Hello")

# This prints Hello 100 times! Much better than copying/pasting 100 lines!

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


#### EXAMPLE 2: Student Marks Scenario (Beginner)

Scenario: Teacher has 5 students' marks. Print each mark.

In [ ]:
marks = [85, 92, 78, 95, 88,45,67,89,34,78]

print(marks[0])
print(marks[1])
print(marks[2])
print(marks[3])
print(marks[4])

85
92
78
95
88


In [ ]:
marks = [85, 92, 78, 95, 88]
#         0   1   2   3   4  (These are indices)

for i in range(5):
    print(marks[i])

85
92
78
95
88


In [ ]:
# Have a look on the iteration:
for i in range(5):
    print(i)

0
1
2
3
4


#### EXAMPLE 3: Student Marks (Smarter Way)

In [ ]:
marks = [85, 92, 78, 95, 88]

# Looping directly through marks (easier!)
for marks in marks:
    print(marks)

85
92
78
95
88


Difference: This is cleaner - Python gives us each mark directly!

#### EXAMPLE 4: Student Marks with Processing
Scenario: Check if each student passed (>= 40)

In [ ]:
marks = [85, 95, 35, 95, 88]
students = ["Rohit", "Akash", "Rohan", "Sara", "Anita"]

for i in range(5):
    student_name = students[i]
    student_mark = marks[i]

    if student_mark >= 40:
        print(student_name + " PASSED with " + str(student_mark))
    else:
        print(student_name + " FAILED with " + str(student_mark))

Rohit PASSED with 85
Akash PASSED with 95
Rohan FAILED with 35
Sara PASSED with 95
Anita PASSED with 88


In [ ]:
marks = [85, 95, 35, 95, 88]
students = ["Rohit", "Akash", "Rohan", "Sara", "Anita"]

for i in range(5):
    student_name = students[i]
    student_mark = marks[i]

    if student_mark >= 40:
        print(f"{student_name} PASSED with {student_mark}")
    else:
        print(f"{student_name} FAILED with {student_mark}")

Rohit PASSED with 85
Akash PASSED with 95
Rohan FAILED with 35
Sara PASSED with 95
Anita PASSED with 88


### TYPE 2: WHILE LOOPS

Real-World Scenario: How a Student Studies

Human student: "I'll study until I understand this topic"

- Keeps studying
- When understood → Stops
- Condition-based, not fixed times

This is like a WHILE loop!

BASIC EXAMPLE: Adding 1 to X Five Times
Without a loop:

In [ ]:
x = 0
print(x)
x = x + 1
print(x)
x = x + 1
print(x)
x = x + 1
print(x)
x = x + 1
print(x)
x = x + 1

print(x)  # Output: 5

0
1
2
3
4
5


In [ ]:
count = 0

while count < 5:
    count = count + 1
    print(count)

print(f"the loop stopped here {count}")  # Output: 5

1
2
3
4
5
the loop stopped here 5


In [ ]:
count = 0
count = count + 1
print(count)
count = count + 1
print(count)
count = count + 1
print(count)
count = count + 1
print(count)
count = count + 1
print(count)

1
2
3
4
5


In [ ]:
print(5 < 5)
print(5 == 5)

False
True


#### EXAMPLE 1: Adding Until Condition Met

In [ ]:
x = 0
count = 0

# Loop while count is less than 5
while count < 20:
    x = x + 1
    count = count + 2
    print("Count: " + str(count) + ", X: " + str(x))

print("Final X: " + str(x))

# or
print(f"Final X: {x}")

Count: 2, X: 1
Count: 4, X: 2
Count: 6, X: 3
Count: 8, X: 4
Count: 10, X: 5
Count: 12, X: 6
Count: 14, X: 7
Count: 16, X: 8
Count: 18, X: 9
Count: 20, X: 10
Final X: 10
Final X: 10


#### EXAMPLE 2: Student Marks - Keep Adding Until Sum Reaches Target

Scenario: Keep adding student marks until total reaches 300

In [ ]:
marks = [85, 92, 78, 95, 88, 75, 90]
total = 0
index = 0

while total < 300:
    total = total + marks[index]
    print("Added " + str(marks[index]) + ", Total: " + str(total))
    index = index + 1

print("Reached target! Total: " + str(total))

Added 85, Total: 85
Added 92, Total: 177
Added 78, Total: 255
Added 95, Total: 350
Reached target! Total: 350


In [ ]:
# # BeeakDown - ignore the below code for now, it only understanding the output.

marks = [85, 92, 78, 95, 88, 75, 90]
total = 0
index = 0
iteration = 1

print("Iteration | Index | Current Total | Mark Added | New Total")
print("-------------------------------------------------------------")

while total < 300:
    current_total = total
    mark = marks[index]
    total += mark
    print(f"{iteration:^9}|{index:^7}|{current_total:^15}|{mark:^11}|{total:^10}")
    index += 1
    iteration += 1

print("\nReached target! Final Total:", total)

Iteration | Index | Current Total | Mark Added | New Total
-------------------------------------------------------------
    1    |   0   |       0       |    85     |    85    
    2    |   1   |      85       |    92     |   177    
    3    |   2   |      177      |    78     |   255    
    4    |   3   |      255      |    95     |   350    

Reached target! Final Total: 350


#### EXAMPLE 3: Student Guessing Game
Scenario: Student keeps guessing marks until correct answer

In [ ]:
correct_mark = 94
guess = 0

while guess != correct_mark:
    guess = int(input("Guess the mark (between 0-100): "))

    if guess < correct_mark:
        print("Too low! Try again.")
    elif guess > correct_mark:
        print("Too high! Try again.")
    else:
        print(f"Correct! The mark is {correct_mark}!")

Correct! The mark is 94!


How it works:

- Loop continues WHILE guess is NOT equal to 85
- When user enters 85, condition becomes False → Loop stops

### TYPE 3: LOOP CONTROL - break, continue, pass

- Real-World Scenario
- break: Student is reading textbook, finds wrong information → STOPS reading that chapter
- continue: Teacher checking marks, skips absent student → MOVES TO NEXT student
- pass: Placeholder for code being written later → DOES NOTHING for now

**BREAK:** Stop the Loop Immediately

Syntax:

In [ ]:
for i in range(10):
    if i == 5:
        break  # Stop here, don't continue
    print(i)

0
1
2
3
4


In [ ]:
for i in range(10):
    if i == 5:
        break  # Stop here, don't continue
    print(i)

0
1
2
3
4


The loop stopped when i became 5!

#### BREAK Example: Student Marks - Stop When Fail Found

Scenario: Check marks until finding first failure

In [ ]:
marks = [85, 92, 35, 95, 88]
students = ["Alex", "Ron", "Harry", "Malfoy", "Jack"]

print("Checking student marks...")

for i in range(5):
    if marks[i] < 40:
        print(students[i] + " FAILED! Stopping check.")
        break  # Stop the loop here
    else:
        print(students[i] + " PASSED with " + str(marks[i]))

Checking student marks...
Alex PASSED with 85
Ron PASSED with 92
Harry FAILED! Stopping check.


In [ ]:
marks = [85, 92, 35, 95, 88]
students = ["Alex", "Ron", "Harry", "Malfoy", "Jack"]

print("Checking student marks...")

for i in range(5):
    if marks[i] < 40:
        print(f"{students[i]} FAILED! Stopping check.")
        break  # Stop the loop here
    else:
        print(f"students[i] PASSED with {marks[i]}")

Checking student marks...
students[i] PASSED with 85
students[i] PASSED with 92
Harry FAILED! Stopping check.


#### CONTINUE: Skip Current Loop, Go to Next

In [ ]:
for i in range(5):
    if i == 2:
        continue  # Skip this, go to next
    print(i)

0
1
3
4


Notice: 2 is missing! It was skipped.

#### CONTINUE Example: Student Marks - Skip Absent Students
Scenario: Print only marks of present students (skip absent)

In [ ]:
marks = [85, 92, 0, 95, 88]  # 0 means absent
students =["Alex", "Ron", "Harry", "Malfoy", "Jack"]
present = [True, True, False, True, True]  # False = absent

for i in range(5):
    if not present[i]:
        continue  # Skip absent students

    print(students[i] + " marked " + str(marks[i]))

Alex marked 85
Ron marked 92
Malfoy marked 95
Jack marked 88


Harry was skipped (absent)!

#### PASS: Do Nothing (Placeholder)

When to use: You're writing code but not ready to add body yet

In [ ]:
for i in range(5):
    print(i)
    if i == 2:
        pass  # Will add code here later
    print("---")

0
---
1
---
2
---
3
---
4
---


#### PASS Example: Student Marks - Placeholder

In [ ]:
marks = [85, 92, 78, 95, 88]

for mark in marks:
    if mark >= 80:
        pass
    else:
        print("Mark needs improvement: " + str(mark))

Mark needs improvement: 78


Key Concepts Summary 🎯

- ✅ FOR loop = Fixed number of repeats (best for lists)
- ✅ WHILE loop = Repeat until condition changes
- ✅ BREAK = Exit the loop completely
- ✅ CONTINUE = Skip current iteration, go to next
- ✅ PASS = Placeholder, does nothing

# Day 10: List Comprehension with For and While Loops

### What is List Comprehension?

**What is List Comprehension?**

Real-World Scenario: Processing Student Data
Without List Comprehension (Manual Way):
A teacher has 5 student marks [85, 92, 78, 95, 88] and needs to create a list of all marks multiplied by 1.5 (for bonus points).



```
# The teacher manually does:

85 × 1.5 = 127.5
92 × 1.5 = 138
78 × 1.5 = 117
95 × 1.5 = 142.5
88 × 1.5 = 132
```



## Let's try with the Append

### Using for loop with append()

In [ ]:
squares = []
for i in range(1, 6):
    squares.append(i * i)
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
squares = []
for i in range(1,21):
    squares.append(i*i)
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [ ]:
# Add numbers 1 to 5:

nums = []
for i in range(1, 6):
    nums.append(i)

print(nums)

[1, 2, 3, 4, 5]


In [ ]:
print(nums)

[1, 2, 3, 4, 5]


In [ ]:
# Add squares of 1 to 3:

squares = []
for i in range(1, 4):
    squares.append(i * i)

print(squares)

[1, 4, 9]


In [ ]:
# Add letters from "Hi"

letters = []
for ch in "Hi":
    letters.append(ch)

In [ ]:
print(letters)

['H', 'i']


In [ ]:
# Add first 3 multiples of 5
multiples = []
for i in range(1, 4):
    multiples.append(i * 5)

In [ ]:
multiples

[5, 10, 15]

### Using while loop with append()

In [ ]:
# Add numbers 1 to 5
nums = []
i = 1
while i <= 5:
    nums.append(i)
    i += 1

In [ ]:
nums

[1, 2, 3, 4, 5]

In [ ]:
# Add squares of 1 to 3
squares = []
i = 1
while i <= 3:
    squares.append(i * i)
    i += 1

In [ ]:
squares

[1, 4, 9]

In [ ]:
# Add letters from "OK"
letters = []
word = "OK"
i = 0
while i < len(word):
    letters.append(word[i])
    i += 1

In [ ]:
letters

['O', 'K']

In [ ]:
# Add even numbers up to 6
evens = []
i = 2
while i <= 6:
    evens.append(i)
    i += 2

In [ ]:
evens

[2, 4, 6]

In [ ]:
# Add first 3 multiples of 3
multiples = []
i = 1
while i <= 3:
    multiples.append(i * 3)
    i += 1

In [ ]:
multiples

[3, 6, 9]

**With List Comprehension (Smart Way):**

Give Python the instruction: "For each mark, multiply by 1.5"
Python automatically creates the new list!


## Understanding the Problem First

BREAKDOWN: Without Loops (Manual Method)

Let's say we have marks: [85, 92, 78, 95, 88]

We want to multiply each by 1.5 for bonus points.

How would we do it WITHOUT any loop?


In [ ]:
marks = [85, 92, 78, 95, 88]

# Without loops - Manual and tedious!
bonus_marks_1 = 85 * 1.5
bonus_marks_2 = 92 * 1.5
bonus_marks_3 = 78 * 1.5
bonus_marks_4 = 95 * 1.5
bonus_marks_5 = 88 * 1.5

print(bonus_marks_1)  # 127.5
print(bonus_marks_2)  # 138.0
print(bonus_marks_3)  # 117.0
print(bonus_marks_4)  # 142.5
print(bonus_marks_5)  # 132.0

127.5
138.0
117.0
142.5
132.0




```
>> Problems:

Repetitive
If we have 1000 marks, we'd write 1000 lines!
Error-prone
Hard to maintain
```



## SOLUTION 1: Using FOR Loop (Traditional Way)

> Understanding FOR Loop Line-by-Line

In [ ]:
marks = [85, 92, 78, 95, 88]
bonus_marks = []  # Empty list to store results

for mark in marks:
    #   ↑       ↑ marks
    #   │       └─ The list we're looping through
    #   └─ Variable holding each mark (85, then 92, then 78...)

    bonus_mark = mark * 1.5
    #             ↑
    #             └─ Calculate bonus for this mark

    bonus_marks.append(bonus_mark)
    #              ↑
    #              └─ Add the result to our list

print(bonus_marks)
# Output: [127.5, 138.0, 117.0, 142.5, 132.0]

[127.5, 138.0, 117.0, 142.5, 132.0]




```
Iteration 1: mark = 85    → bonus_mark = 127.5  → bonus_marks = [127.5]
Iteration 2: mark = 92    → bonus_mark = 138.0  → bonus_marks = [127.5, 138.0]
Iteration 3: mark = 78    → bonus_mark = 117.0  → bonus_marks = [127.5, 138.0, 117.0]
Iteration 4: mark = 95    → bonus_mark = 142.5  → bonus_marks = [127.5, 138.0, 117.0, 142.5]
Iteration 5: mark = 88    → bonus_mark = 132.0  → bonus_marks = [127.5, 138.0, 117.0, 142.5, 132.0]
```



In [ ]:
# Define the breakdown data of above code

# Note: follow the output only.
parts = [
    ["Part", "Name", "What It Does"],
    ["for", "Keyword", "Start a loop"],
    ["mark", "Loop Variable", "Holds current item (85, 92, 78, 95, 88)"],
    ["in", "Keyword", '"For each item in"'],
    ["marks", "Iterable", "The list we're going through"],
    [":", "Colon", "Here comes the body"],
    ["bonus_marks = []", "Initialization", "Start with empty list"],
    ["bonus_mark = mark * 1.5", "Processing", "Transform the data"],
    ["bonus_marks.append()", "List Method", "Add result to list"]
]

# Print the table with box formatting
print("+------------------------+------------------+-------------------------------+")
for row in parts:
    print(f"| {row[0]:<22} | {row[1]:<16} | {row[2]:<29} |")
    print("+------------------------+------------------+-------------------------------+")

+------------------------+------------------+-------------------------------+
| Part                   | Name             | What It Does                  |
+------------------------+------------------+-------------------------------+
| for                    | Keyword          | Start a loop                  |
+------------------------+------------------+-------------------------------+
| mark                   | Loop Variable    | Holds current item (85, 92, 78, 95, 88) |
+------------------------+------------------+-------------------------------+
| in                     | Keyword          | "For each item in"            |
+------------------------+------------------+-------------------------------+
| marks                  | Iterable         | The list we're going through  |
+------------------------+------------------+-------------------------------+
| :                      | Colon            | Here comes the body           |
+------------------------+------------------+---------

## EXAMPLE 1: For Loop - Square All Marks

Scenario: Convert all marks to squared values (85² = 7225)

In [ ]:
marks = [85, 92, 78, 95, 88]
squared_marks = []

print("Original marks:", marks)
print("\nSquaring each mark:\n")

for mark in marks:
    squared = mark * mark
    print("Mark: " + str(mark) + " → Squared: " + str(squared))
    squared_marks.append(squared)


print(f"Squared marks {squared_marks}")

Original marks: [85, 92, 78, 95, 88]

Squaring each mark:

Mark: 85 → Squared: 7225
Mark: 92 → Squared: 8464
Mark: 78 → Squared: 6084
Mark: 95 → Squared: 9025
Mark: 88 → Squared: 7744
Squared marks [7225, 8464, 6084, 9025, 7744]


## EXAMPLE 2: For Loop - Filter Passing Marks (>= 80)

Scenario: Create a list of only passing marks (80 and above)

In [ ]:
all_marks = [85, 92, 78, 95, 88, 75, 90]
passing_marks = []

print("All marks:", all_marks)
print("\nFiltering marks >= 80:\n")

for mark in all_marks:
    if mark >= 80:
        print("✓ Mark " + str(mark) + " is PASSING")
        passing_marks.append(mark)
    else:
        print("✗ Mark " + str(mark) + " is FAILING")

print("\nPassing marks only:", passing_marks)

All marks: [85, 92, 78, 95, 88, 75, 90]

Filtering marks >= 80:

✓ Mark 85 is PASSING
✓ Mark 92 is PASSING
✗ Mark 78 is FAILING
✓ Mark 95 is PASSING
✓ Mark 88 is PASSING
✗ Mark 75 is FAILING
✓ Mark 90 is PASSING

Passing marks only: [85, 92, 95, 88, 90]


## EXAMPLE 3: For Loop - Convert String Marks to Numbers

Scenario: User gives marks as text, convert to numbers

In [ ]:
mark_strings = ["85", "92", "78", "95", "88"]
mark_numbers = []

print("Original (Text):", mark_strings)
print("Data type:", type(mark_strings[0]))
print("\nConverting to numbers:\n")

for mark_str in mark_strings:
    mark_num = int(mark_str)
    print("Text: '" + mark_str + "' → Number: " + str(mark_num))
    mark_numbers.append(mark_num)

print("\nConverted (Numbers):", mark_numbers)
print("Data type:", type(mark_numbers[0]))

Original (Text): ['85', '92', '78', '95', '88']
Data type: <class 'str'>

Converting to numbers:

Text: '85' → Number: 85
Text: '92' → Number: 92
Text: '78' → Number: 78
Text: '95' → Number: 95
Text: '88' → Number: 88

Converted (Numbers): [85, 92, 78, 95, 88]
Data type: <class 'int'>


In [ ]:
marks = ["85", "92", "78", "95", "88"]

## SOLUTION 2: Using WHILE Loop

Understanding WHILE Loop Line-by-Line

In [ ]:
marks = [85, 92, 78, 95, 88]
bonus_marks = []
index = 0  # Start from first position

while index < len(marks):
      #  ↑
      #  └─ Continue looping WHILE index is less than list length

    mark = marks[index]
    #               ↑
    #               └─ Get mark at current position

    bonus_mark = mark * 1.5
    bonus_marks.append(bonus_mark)

    index = index + 1
    #       ↑
    #       └─ Move to next position

print(bonus_marks)
# Output: [127.5, 138.0, 117.0, 142.5, 132.0]

[127.5, 138.0, 117.0, 142.5, 132.0]


Step-by-Step Execution:



```
Initial: index = 0, bonus_marks = []

Iteration 1: index = 0, mark = marks[0] = 85    → bonus_mark = 127.5  → bonus_marks = [127.5]      → index = 1
Iteration 2: index = 1, mark = marks[1] = 92    → bonus_mark = 138.0  → bonus_marks = [127.5, 138.0]      → index = 2
Iteration 3: index = 2, mark = marks[2] = 78    → bonus_mark = 117.0  → bonus_marks = [127.5, 138.0, 117.0] → index = 3
Iteration 4: index = 3, mark = marks[3] = 95    → bonus_mark = 142.5  → bonus_marks = [127.5, 138.0, 117.0, 142.5]     → index = 4
Iteration 5: index = 4, mark = marks[4] = 88    → bonus_mark = 132.0  → bonus_marks = [127.5, 138.0, 117.0, 142.5, 132.0] → index = 5

Check: index = 5, len(marks) = 5 → 5 < 5 is False → Loop stops
```



### While Loop - Grade Calculation

Scenario: Calculate grade for each mark (A: 90+, B: 80+, C: 70+, etc.)

In [ ]:
marks = [85, 92, 78, 95, 88]
grades = []
index = 0

print("Calculating grades:\n")

while index < len(marks):
    mark = marks[index]

    if mark >= 90:
        grade = "A"
    elif mark >= 80:
        grade = "B"
    elif mark >= 70:
        grade = "C"
    else:
        grade = "F"

    print("Mark: " + str(mark) + " → Grade: " + grade)
    grades.append(grade)
    index = index + 1

print("\nAll grades:", grades)

Calculating grades:

Mark: 85 → Grade: B
Mark: 92 → Grade: A
Mark: 78 → Grade: C
Mark: 95 → Grade: A
Mark: 88 → Grade: B

All grades: ['B', 'A', 'C', 'A', 'B']


## While Loop - Find First Passing Mark

Scenario: Find the first mark that's >= 80

In [ ]:
marks = [75, 78, 70, 92, 88]
index = 0
found = False

print("Looking for first mark >= 80:\n")

while index < len(marks) and not found:
    mark = marks[index]
    print("Checking mark at position " + str(index) + ": " + str(mark))

    if mark >= 80:
        print("✓ Found! First passing mark is: " + str(mark))
        found = True
    else:
        print("✗ Not passing yet, continue...\n")

    index = index + 1

if not found:
    print("No passing marks found!")

Looking for first mark >= 80:

Checking mark at position 0: 75
✗ Not passing yet, continue...

Checking mark at position 1: 78
✗ Not passing yet, continue...

Checking mark at position 2: 70
✗ Not passing yet, continue...

Checking mark at position 3: 92
✓ Found! First passing mark is: 92


### DATA SCIENCE APPLICATION

#### Real-World Data Science Scenario: Student Performance Analysis

####Dataset: Student marks from an exam



```
Student Names: ["Alex", "Sam", "Ron", "Zara", "Max", "Mike", "Rob"]
Marks:         [85,    92,    78,    95,    88,     76,     90]
```



In [ ]:
marks = [85, 92, 78, 95, 88, 76, 90]

total = 85 + 92 + 78 + 95 + 88 + 76 + 90
count = 7
average = total / count

print("Total:", total)      # 604
print("Count:", count)      # 7
print("Average:", average)  # 86.28...

Total: 604
Count: 7
Average: 86.28571428571429


## With FOR Loop (Smart):

In [ ]:
marks = [85, 92, 78, 95, 88, 76, 90]
total = 0
count = 0

print("Calculating average:\n")

for mark in marks:
    print("Adding mark: " + str(mark))
    total = total + mark
    count = count + 1

average = total / count

print("\nTotal sum:", total)
print("Number of marks:", count)
print("Average:", average)

Calculating average:

Adding mark: 85
Adding mark: 92
Adding mark: 78
Adding mark: 95
Adding mark: 88
Adding mark: 76
Adding mark: 90

Total sum: 604
Number of marks: 7
Average: 86.28571428571429


## Data Science EXAMPLE 2: Identify Below-Average Students Using FOR Loop

Scenario: Find students who scored below average

In [ ]:
students = ["Alex", "Sam", "Ron", "Zara", "Max", "Mike", "Rob"]
marks = [85, 92, 78, 95, 88, 76, 90]

# First, calculate average
total = 0
for mark in marks:
    total = total + mark

average = total / len(marks)

print("Class Average:", average)
print("\n" + "="*50)
print("Students Below Average (Need Help):\n")

below_average_students = []

# Now find below average
for i in range(len(students)):
    student_name = students[i]
    student_mark = marks[i]

    if student_mark < average:
        difference = average - student_mark
        print("Name: " + student_name)
        print("Mark: " + str(student_mark))
        print("Below average by: " + str(round(difference, 2)))
        print("---")

        below_average_students.append(student_name)

print("Students needing help:", below_average_students)

Class Average: 86.28571428571429

Students Below Average (Need Help):

Name: Alex
Mark: 85
Below average by: 1.29
---
Name: Ron
Mark: 78
Below average by: 8.29
---
Name: Mike
Mark: 76
Below average by: 10.29
---
Students needing help: ['Alex', 'Ron', 'Mike']


## Data Science EXAMPLE 3: Performance Categorization Using WHILE Loop

Scenario: Categorize students into performance tiers

In [ ]:
students = ["Alex", "Sam", "Ron", "Zara", "Max", "Mike", "Rob"]
marks = [85, 92, 78, 95, 88, 76, 90]

excellent = []   # 90+
good = []        # 80-89
average = []     # 70-79
poor = []        # <70

index = 0

print("Categorizing student performance:\n")

while index < len(students):
    student_name = students[index]
    mark = marks[index]

    print("Processing: " + student_name + " (" + str(mark) + ") →", end=" ")

    if mark >= 90:
        category = "EXCELLENT"
        excellent.append(student_name)
    elif mark >= 80:
        category = "GOOD"
        good.append(student_name)
    elif mark >= 70:
        category = "AVERAGE"
        average.append(student_name)
    else:
        category = "POOR"
        poor.append(student_name)

    print(category)
    index = index + 1

print("\n" + "="*50)
print("PERFORMANCE REPORT:\n")
print("EXCELLENT (90+):", excellent)
print("GOOD (80-89):", good)
print("AVERAGE (70-79):", average)
print("POOR (<70):", poor)

Categorizing student performance:

Processing: Alex (85) → GOOD
Processing: Sam (92) → EXCELLENT
Processing: Ron (78) → AVERAGE
Processing: Zara (95) → EXCELLENT
Processing: Max (88) → GOOD
Processing: Mike (76) → AVERAGE
Processing: Rob (90) → EXCELLENT

PERFORMANCE REPORT:

EXCELLENT (90+): ['Sam', 'Zara', 'Rob']
GOOD (80-89): ['Alex', 'Max']
AVERAGE (70-79): ['Ron', 'Mike']
POOR (<70): []


# Day 11: Dynamic and Immutable Data Structures – Sets


What are Sets?

Imagine you're organizing a party and keeping track of who's coming. You don't want duplicate names on your guest list, and you don't care about the order. This is exactly what a Set does in Python!

A Set is an unordered collection of unique items. Think of it like a bag of unique items where:

- ❌ No duplicates allowed
- ❌ No specific order (can't access by index)

- ✅ Very fast for checking membership
- ✅ Perfect for removing duplicates

Real-World Analogy: University Student Enrollment System

In [ ]:
# Students enrolled in different courses
math_students = {"Alice", "Bob", "Charlie", "David"}
physics_students = {"Bob", "David", "Emma", "Frank"}
chemistry_students = {"Charlie", "Emma", "Grace"}

In [ ]:
print(math_students)
print(physics_students)
print(chemistry_students)

{'David', 'Charlie', 'Bob', 'Alice'}
{'Emma', 'David', 'Frank', 'Bob'}
{'Emma', 'Grace', 'Charlie'}


In [ ]:
# Method 1: Using curly braces
fruits = {"apple", "banana", "orange"}

In [ ]:
print(fruits)

{'banana', 'orange', 'apple'}


In [ ]:
# Method 2: Using set() constructor
numbers = set([1, 2, 3, 4, 5])

In [ ]:
# Creating empty set (⚠️ {} creates a dict, not a set!)
empty_set = set()  # Correct
# empty_set = {}   # Wrong! This is a dictionary

In [ ]:
# Sets automatically remove duplicates
duplicate_numbers = {1, 2, 2, 3, 3, 3, 4}
print(duplicate_numbers)

{1, 2, 3, 4}


### Lists vs Sets: The Key Differences

| Feature     | List                            | Set                                         |
|-------------|----------------------------------|---------------------------------------------|
| **Syntax**  | `[1, 2, 3]`                     | `{1, 2, 3}`                                 |
| **Order**   | ✅ Ordered (maintains insertion order) | ❌ Unordered (no guaranteed order)     |
| **Duplicates** | ✅ Allows duplicates             | ❌ No duplicates (automatically removes)     |
| **Indexing**   | ✅ Supports indexing `list[0]`   | ❌ No indexing                              |
| **Mutable**    | ✅ Can modify elements           | ✅ Can add/remove, but items must be immutable |
| **Speed**      | 🐢 Slower for membership testing | ⚡ Very fast for membership testing         |
| **Use Case**   | When order matters, need duplicates | When uniqueness matters, need fast lookup |


Practical Comparison Example

In [ ]:
# LIST - Shopping cart (order matters, duplicates allowed)
shopping_cart = ["apple", "banana", "apple", "orange"]
print(shopping_cart[0])  # Can access by index: "apple"
print(len(shopping_cart))  # 4 items (duplicates counted)

apple
4


In [ ]:
# SET - Unique items you need to buy
items_to_buy = {"apple", "banana", "orange"}
# print(items_to_buy[0])  # ❌ Error! Sets don't support indexing
print(len(items_to_buy))  # 3 items (only unique items)

# Speed comparison for membership testing
# "apple" in shopping_cart  # Slower (checks each item)
# "apple" in items_to_buy   # Faster (uses hash lookup)

3


### Essential Set Methods

----
1. .add() - Add a Single Item

Real-World Example: Adding a new student to a course

----

In [ ]:
enrolled_students = {"Alice", "Bob", "Charlie"}
print("Before:", enrolled_students)

Before: {'Alice', 'Charlie', 'Bob'}


In [ ]:
# New student enrolls
enrolled_students.add("David")
print("After adding David:", enrolled_students)

After adding David: {'David', 'Alice', 'Charlie', 'Bob'}


In [ ]:
# Adding duplicate has no effect
enrolled_students.add("Alice")
print("After adding Alice again:", enrolled_students)  # No change!

After adding Alice again: {'David', 'Alice', 'Charlie', 'Bob'}


----

2. .update() - Add Multiple Items

Real-World Example: Batch enrollment of students

----

In [ ]:
enrolled_students = {"Alice", "Bob"}
print("Initial students:", enrolled_students)

Initial students: {'Alice', 'Bob'}


In [ ]:
# Add multiple students at once
new_students = ["Charlie", "David", "Emma"]

In [ ]:
enrolled_students.update(new_students)
print("After batch enrollment:", enrolled_students)

After batch enrollment: {'David', 'Alice', 'Bob', 'Emma', 'Charlie'}


In [ ]:
# You can also update with another set
transfer_students = {"Frank", "Grace"}
enrolled_students.update(transfer_students)
print("After transfers:", enrolled_students)

After transfers: {'David', 'Frank', 'Alice', 'Bob', 'Emma', 'Charlie', 'Grace'}


----
3. .remove() - Remove an Item (Raises Error if Not Found)

Real-World Example: Student drops the course

----

In [ ]:
enrolled_students = {"Alice", "Bob", "Charlie", "David"}
print("Before:", enrolled_students)

# Student drops the course
enrolled_students.remove("Bob")
print("After Bob drops:", enrolled_students)

# ⚠️ Trying to remove non-existent item causes error
# enrolled_students.remove("Zack")  # KeyError!

Before: {'David', 'Alice', 'Charlie', 'Bob'}
After Bob drops: {'David', 'Alice', 'Charlie'}


----
4. .discard() - Remove an Item (No Error if Not Found)

Real-World Example: Safe removal without knowing if item exists

----

In [ ]:
enrolled_students = {"Alice", "Bob", "Charlie"}

# Remove if exists, do nothing if doesn't exist
enrolled_students.discard("Bob")  # Removes Bob
print(enrolled_students)

{'Alice', 'Charlie'}


In [ ]:
enrolled_students.discard("Zack")  # No error, just continues
print(enrolled_students)  # Same as before

{'Alice', 'Charlie'}


----

5. pop() - Remove and Return Random Item

----

In [ ]:
lottery_participants = {"Alice", "Bob", "Charlie", "David", "Emma"}
print("Participants:", lottery_participants)

# Pick random winner
winner = lottery_participants.pop()
print(f"Winner: {winner}")
print("Remaining participants:", lottery_participants)

Participants: {'Emma', 'David', 'Charlie', 'Alice', 'Bob'}
Winner: Emma
Remaining participants: {'David', 'Charlie', 'Alice', 'Bob'}


----

6. .clear() - Remove All Items

----

In [ ]:
temp_data = {"item1", "item2", "item3"}
print("Before clear:", temp_data)

temp_data.clear()
print("After clear:", temp_data)  # set()

Before clear: {'item1', 'item2', 'item3'}
After clear: set()


----

7. .copy() - Create a Shallow Copy

----

In [ ]:
original = {"apple", "banana", "cherry"}
duplicate = original.copy()

duplicate.add("orange")
print("Original:", original)    # Unchanged
print("Duplicate:", duplicate)  # Has orange

Original: {'banana', 'cherry', 'apple'}
Duplicate: {'banana', 'cherry', 'orange', 'apple'}


# Day 12: Topic: Python Dictionary (`dict`)

###  What Is a Dictionary?

A **dictionary** in Python is a built-in data structure that stores data in **key-value pairs**.  
It’s like a real-world dictionary: you look up a **word (key)** to find its **meaning (value)**.

---

###  Where Is It Used?

- Widely used in **data science**, **web development**, and **API responses**
- Helps organize data like:
  - Student records
  - JSON data from APIs
  - Model configurations
  - Feature mappings

---

###  How to Create a Dictionary

####  Syntax:

```python
dictionary_name = {
    'key1': value1,
    'key2': value2,
    ...
}


In [ ]:
player = {
    'name': 'MS Dhoni',
    'role': 'Captain & Wicket Keeper',
    'team': 'India',
    'achievements': ['World Cup 2011', 'Champions Trophy 2013']
}


In [ ]:
print(player['name'])
print(player['achievements'])

MS Dhoni
['World Cup 2011', 'Champions Trophy 2013']


##  Dictionary Concepts in Python

| Concept  | Description                             |
|----------|-----------------------------------------|
| `key`    | Identifier used to access a value       |
| `value`  | Data associated with the key            |
| `{}`     | Used to define a dictionary             |
| `[]`     | Used to access a value by its key       |
| `dict()` | Alternate way to create a dictionary    |


## Common Dictionary Methods in Python

| Method            | Description                                                                 |
|-------------------|-----------------------------------------------------------------------------|
| `.get(key)`       | Returns the value for the given key. Returns `None` if key is not found.    |
| `.keys()`         | Returns a view object of all keys in the dictionary.                        |
| `.values()`       | Returns a view object of all values in the dictionary.                      |
| `.items()`        | Returns a view object of all key-value pairs as tuples.                     |
| `.update(dict2)`  | Updates the dictionary with key-value pairs from another dictionary.        |
| `.pop(key)`       | Removes the specified key and returns its value.                            |
| `.popitem()`      | Removes and returns the last inserted key-value pair (Python 3.7+).         |
| `.clear()`        | Removes all items from the dictionary.                                      |
| `.copy()`         | Returns a shallow copy of the dictionary.                                   |
| `del dict[key]`   | Deletes the specified key from the dictionary.                              |
| `dict()`          | Creates a new dictionary (constructor method).                              |

---

###  Example Usage

```python
player = {
    'name': 'MS Dhoni',
    'role': 'Captain',
    'team': 'India'
}

print(player.get('name'))       # Output: MS Dhoni
print(player.keys())            # Output: dict_keys(['name', 'role', 'team'])
print(player.values())          # Output: dict_values(['MS Dhoni', 'Captain', 'India'])
print(player.items())           # Output: dict_items([('name', 'MS Dhoni'), ('role', 'Captain'), ('team', 'India')])


In [ ]:
player = {
    'name': 'MS Dhoni',
    'role': 'Captain',
    'team': 'India'
}

### 1. get()

In [ ]:
print(player.get('name'))
print(player.get('age'))   # Output: None (key doesn't exist)

MS Dhoni
None


- .get(key) safely returns the value for the given key.

- If the key doesn't exist, it returns None instead of throwing an error.

- You can also provide a default value: player.get('age', 'Not Available')

### 2. keys()

In [ ]:
print(player.values())

dict_values(['MS Dhoni', 'Captain', 'India'])


- Returns a view object of all values.

- Useful when you want to loop through values only.

### 3. values()

In [ ]:
print(player.values())

dict_values(['MS Dhoni', 'Captain', 'India'])


- Returns a view object of all values.

- Useful when you want to loop through values only.

### 4. items()

In [ ]:
print(player.items())

dict_items([('name', 'MS Dhoni'), ('role', 'Captain'), ('team', 'India')])


- Returns all key-value pairs as tuples inside a view object.

In [ ]:
# Useful for looping with both key and value:
for k, v in player.items():
    print(k, "→", v)

name → MS Dhoni
role → Captain
team → India


### 5. update()

In [ ]:
player.update({'age': 39})
print(player)

{'name': 'MS Dhoni', 'role': 'Captain', 'team': 'India', 'age': 39}


- Adds or updates key-value pairs.
- If the key exists, it overwrites the old value.

### 6. pop()

In [ ]:
print(player.pop('role'))
# ✅ Output: Captain
print(player)

Captain
{'name': 'MS Dhoni', 'team': 'India', 'age': 39}


- Removes the key and returns its value.
- Raises KeyError if the key doesn't exist.

### 7. popitem()

In [ ]:
print(player.popitem())

('age', 39)


In [ ]:
print(player)

{'name': 'MS Dhoni', 'team': 'India'}


- Removes and returns the last inserted key-value pair.
- Raises KeyError if the dictionary is empty.

### 8. clear()

In [ ]:
player.clear()
print(player)

{}


- Removes all items from the dictionary.
- After this, the dictionary is empty = {}

### 9. copy()

In [ ]:
player = {'name': 'MS Dhoni', 'team': 'India'}
backup = player.copy()
print(backup)

{'name': 'MS Dhoni', 'team': 'India'}


- Creates a shallow copy of the dictionary.
- Changes to backup won’t affect player.

### 10. del keyword

In [ ]:
del player['team']
print(player)

{'name': 'MS Dhoni'}


- Deletes a specific key.
- Raises KeyError if the key doesn’t exist.

###   Examples That Raise `KeyError` in Dictionaries

```python
print(player['age'])  
#  KeyError: 'age' (because 'age' key doesn't exist)

- Direct access using [] will raise an error if the key is missing.
- Use .get('age') instead to avoid crashing.


In [ ]:
# print(player.pop('role'))
# ❌ KeyError if 'role' was already removed or never existed

- .pop() requires the key to exist.
- You can provide a default: player.pop('role', 'Not Found')

In [ ]:
# player.popitem()
# ❌ KeyError if dictionary is empty

- .popitem() removes the last inserted item.
- If the dictionary is empty, this will raise an error

# Day 13 : Topic: Python Function Definition using `def`

##  What is `def`?

- `def` is a **keyword** used to define a **function** in Python.
- A function is a reusable block of code that performs a specific task.
- Functions improve **modularity**, **readability**, and **reusability** in your code.

---

##  Where Is It Used?

- Widely used in **data science**, **machine learning**, **web development**, and **automation**.
- In data science, functions help:
  - Clean data
  - Apply transformations
  - Perform calculations (e.g., mean, standard deviation)
  - Encapsulate model training and evaluation steps

Example (Data Science Context):

```python
def calculate_mean(numbers):
    return sum(numbers) / len(numbers)

data = [10, 20, 30, 40]
print("Mean:", calculate_mean(data))


In [ ]:
# Syntax:
def function_name(parameters):
    # code block
    return result

### Without def: Direct Code Execution

In [ ]:
# Sum of Two Numbers
a = 10
b = 5
sum_result = a + b
print("Sum:", sum_result)

Sum: 15


`Here, we directly add a and b. No function is used. output: Sum: 15`

In [ ]:
# Average of Three Numbers
x = 80
y = 90
z = 100
average = (x + y + z) / 3
print("Average:", average)

Average: 90.0


In [ ]:
# Division
num = 20
den = 4
division = num / den
print("Division:", division)

Division: 5.0


### With def: Using Functions

In [ ]:
# Sum Function
def find_sum(a, b):
    return a + b

print("Sum:", find_sum(10, 5))

Sum: 15


`find_sum` is a user-defined function. a and b are parameters. return sends back the result.

In [ ]:
# Average Function
def find_average(x, y, z):
    return (x + y + z) / 3

print("Average:", find_average(80, 90, 100))

Average: 90.0


`Reusable logic for any three numbers.`

In [ ]:
# Division Function
def divide(num, den):
    return num / den

print("Division:", divide(20, 4))

Division: 5.0


`Handles division cleanly. You can even add error handling later.`

In [ ]:
# Multiplication Using *
def multiply(x, y):
    return x * y

print("Multiplication:", multiply(6, 7))

Multiplication: 42


`* is the multiplication operator. This function multiplies two numbers.`

### Function with Default Parameter

In [ ]:
def greet(name="Student"):
    print(f"Hello, {name}!")

In [ ]:
greet()

Hello, Student!


In [ ]:
greet("Chetan")

Hello, Chetan!


### ✅ Do's and ❌ Don'ts in Python `def` Functions

### ✅ Do's

- Use descriptive function names (`calculate_mean`, `get_grade`)
- Keep functions short and focused on one task
- Use `return` to send back results
- Add comments or docstrings for clarity
- Test your function with different inputs

---

### ❌ Don'ts

- Don’t use vague names like `func1`, `doStuff`
- Don’t write large, multi-purpose functions — break them into smaller ones
- Don’t forget to use `return` if you need the result outside the function
- Don’t modify global variables inside functions unless necessary
- Don’t ignore edge cases (e.g., empty lists, zero division)


----

## Understanding `print` vs `return` in Python Functions

### 🗣️ Let's Talk: Why We Use `return` Instead of Just `print`

When we first learn Python, we often use `print()` to show results. It’s simple and visual — great for beginners! But as we move into **functions**, especially in **data science**, we shift to using `return`. Why?

---

### 🔸 `print()` — Just for Display

- `print()` shows output on the screen.
- It’s useful for **debugging**, **checking values**, or giving feedback to users.
- But it doesn’t give us a value we can **reuse** or **store**.

```python
def show_sum(a, b):
    print(a + b)

show_sum(10, 5)  # Output: 15

=============================================

return — For Reusability and Logic
return sends the result back to the caller.

You can store, pass, or use the returned value in other operations.

This is essential for data pipelines, model training, and modular coding.

In [ ]:
def get_sum(a, b):
    return(a+b)

In [ ]:
result = get_sum(10, 5)
print("Sum is:", result)

Sum is: 15


If you're building a function that calculates something — like average, sum, or prediction — always use return.

If you're just checking values or teaching, print() is fine.

In [ ]:
# Good for learning
def greet(name):
    print(f"Hello, {name}!")

# Good for logic
def square(n):
    return n * n

###  Summary Table: `print()` vs `return`

| Feature        | `print()`             | `return`                          |
|----------------|------------------------|------------------------------------|
| **Purpose**     | Display output         | Send result back to caller         |
| **Reusable?**   | ❌ No                  | ✅ Yes                              |
| **Used for**    | Debugging, messages    | Logic, data flow, modular coding   |
| **Returns value** | ❌ No               | ✅ Yes                              |

---

##  When to Use What

- **Use `print()`** when you want to **see** something (e.g., for debugging or displaying messages).
- **Use `return`** when you want to **use** something (e.g., store, reuse, or pass the result).

## Can `print()` Return Values?

No — `print()` **does not return** values. It only **displays** them on the screen.  
If you want to **use** the result later (e.g., store it, pass it, reuse it), you must use `return`.

---

## Example Using `print()` — Does NOT Return

```python
def show_sum(a, b):
    print(a + b)

result = show_sum(10, 5)
print("Result is:", result)


In [ ]:
def show_sum(a, b):
    print(a + b)

In [ ]:
result = show_sum(10, 5)
print("Result is:", result)

15
Result is: None


####  Why Does `print()` Show `None` in Function Output?

When you use `print()` inside a function **without a `return` statement**, the function itself doesn’t send back any value — it just displays something on the screen.

So when you try to store the result like this:

```python
def show_sum(a, b):
    print(a + b)

result = show_sum(10, 5)
print("Result is:", result)

<output>
15
Result is: None


In [ ]:
# Example Using return — Returns the Value
def get_sum(a, b):
    return a + b

result = get_sum(10, 5)
print("Result is:", result)

Result is: 15


# Day 14: Topic: Function Arguments in Python — `*args` and `**kwargs`

##  Why Do We Use `*args` and `**kwargs`?

In Python, functions often need to handle **flexible numbers of inputs**.  
Instead of hardcoding a fixed number of parameters, we use:

- `*args` → for **any number of positional arguments**
- `**kwargs` → for **any number of keyword arguments**

This makes our functions more **reusable**, **dynamic**, and **scalable** — especially useful in **data science**, where inputs can vary (e.g., multiple features, parameters, or metrics).

---

##  Without `*args`: Fixed Inputs Only

```python
def average(a, b, c):
    return (a + b + c) / 3

print(average(10, 20, 30))  #  Output: 20.0
print(average(10, 20))      #  Error: missing 1 required argument

❌ You must pass exactly 3 arguments.

❌ Not flexible for different input sizes.


### With *args: Accepts Any Number of Positional Inputs

In [ ]:
def average(*args):
    return sum(args) / len(args)

print(average(10, 20, 30))       # Output: 20.0


20.0


In [ ]:
print(average(5, 15, 25, 35))    # Output: 20.0

20.0


In [ ]:
print(average(100))              #  Output: 100.0

100.0


- Accepts any number of values.

- Works for 1, 3, or 10 inputs — no need to rewrite the function.

##  Problem with Fixed Parameters

```python
def function_name(a, b, c, d):
    print(a, b, c, d)

function_name("Rohit", "Mayur", "Aman", "Vijay")

- This works fine.
- ❌ But what if we want to add one more name like "Rahul"?

In [ ]:
'''
function_name("Rohit", "Mayur", "Aman", "Vijay", "Rahul")
# Error: function_name() takes 4 positional arguments but 5 were given
'''

'\nfunction_name("Rohit", "Mayur", "Aman", "Vijay", "Rahul")\n# Error: function_name() takes 4 positional arguments but 5 were given\n'

In [ ]:
def function_name(a, b, c, d):
    print(a, b, c, d)

function_name("Rohit", "Mayur", "Aman", "Vijay")

Rohit Mayur Aman Vijay


In [ ]:
# function_name("Rohit", "Mayur", "Aman", "Vijay", "Rahul")

## Why This Is Not Scalable

- **Every time we want to add or remove names, we’d have to change the function definition.**

- **This is not flexible or scalable — especially in real-world scenarios where input size may vary.**

### Solution: Use *args for Variable-Length Positional Arguments

In [ ]:
def function_name(*args):
    print(args)

In [ ]:
function_name("Rohit", "Mayur", "Aman", "Vijay", "Rahul")

('Rohit', 'Mayur', 'Aman', 'Vijay', 'Rahul')


#### What’s Happening in the Backend?

-- ***args collects all extra positional arguments into a tuple.**

-- **Even if you pass a list, it still gets stored as a tuple inside the function.**

In [ ]:
def function_name(*args):
    print("Stored as:", type(args))
    print("Values:", args)

In [ ]:
function_name("Rohit", "Mayur", "Aman")

Stored as: <class 'tuple'>
Values: ('Rohit', 'Mayur', 'Aman')


In [ ]:
function_name(["Rohit", "Mayur"])

Stored as: <class 'tuple'>
Values: (['Rohit', 'Mayur'],)


### Mixing Normal and Variable Arguments

In [ ]:
def function_name(normal, *args):
    print("Normal argument:", normal)
    print("Other names:", args)

In [ ]:
function_name("Sam", "Rohit", "Mayur", "Aman")

Normal argument: Sam
Other names: ('Rohit', 'Mayur', 'Aman')


### What Is This Called?

**This is called "`Positional Argument` followed by Variable-Length Positional Arguments".**

In [ ]:
def function_name(normal, normal_1, *args):
    print("Normal argument:", normal)
    print("Normal argument_1:", normal_1)
    print("Other names:", args)

In [ ]:
function_name("Sam", "Rohit", "Mayur", "Aman")

Normal argument: Sam
Normal argument_1: Rohit
Other names: ('Mayur', 'Aman')


### Rules to Remember

- *args must come after all normal positional arguments.

- You can pass any number of extra values after the required ones.

- Inside the function, args behaves like a tuple — you can loop, index, or unpack it.

`Use *args when you want your function to accept any number of values without rewriting the function every time.`

#  Practice Problems: `*args` and Positional Arguments in Python

---

##  Part 1: `*args` Based Problems

These problems use `*args` to handle **variable-length positional inputs**.

---

### 1. Sum of All Numbers

```python
def total_sum(*args):
    return sum(args)

print(total_sum(10, 20, 30))        # Output: 60
print(total_sum(5, 15, 25, 35, 45)) # Output: 125

### 2. Multiply All Numbers

def multiply_all(*args):
    result = 1
    for num in args:
        result *= num
    return result

print(multiply_all(2, 3, 4))        # Output: 24
print(multiply_all(1, 5, 10))       # Output: 50


### 3. Average of All Numbers

def average(*args):
    return sum(args) / len(args)

print(average(10, 20, 30))          # Output: 20.0
print(average(5, 15, 25, 35))       # Output: 20.0


### 4. Divide First by Rest (Sequential Division)

def divide_sequence(*args):
    result = args[0]
    for num in args[1:]:
        result /= num
    return result

print(divide_sequence(100, 2, 5))   # Output: 10.0
print(divide_sequence(50, 2, 5))    # Output: 5.0


### 5. Find Maximum Value

def find_max(*args):
    return max(args)

print(find_max(10, 20, 5, 40))      # Output: 40
print(find_max(1, 2, 3))            # Output: 3


-----------------------------------------
## Part 2: Positional Argument Problems
-----------------------------------------

- These problems require fixed inputs before using *args.


6. Greet a Teacher and Students

def greet(teacher, *students):
    print("Teacher:", teacher)
    print("Students:", students)

greet("Prasad", "Amit", "Rohit", "Mayur")    

# Output:
# Teacher: Prasad
# Students: ('Amit', 'Rohit', 'Mayur')

### 7. Calculate Bonus for a Manager and Team

def bonus(manager, *team_scores):
    team_avg = sum(team_scores) / len(team_scores)
    print(f"Manager: {manager}, Team Average Score: {team_avg}")

bonus("Ravi", 80, 85, 90)
# Output: Manager: Ravi, Team Average Score: 85.0

##  More Examples Using Positional + `*args` in Python

These examples combine a **normal argument** with flexible `*args` to handle dynamic inputs — perfect for real-world scenarios like math operations or streaming platforms.

---

### 1. Example: Calculate Total Subscription Cost for a Platform

```python
def subscription_cost(platform, *monthly_prices):
    total = sum(monthly_prices)
    print(f"Platform: {platform}, Total Cost: ₹{total}")

subscription_cost("Hotstar", 149, 149, 149)
# Output: Platform: Hotstar, Total Cost: ₹447

subscription_cost("Netflix", 199, 199, 199, 199)
# Output: Platform: Netflix, Total Cost: ₹796


In [ ]:
def subscription_cost(platform, *monthly_prices):
    total = sum(monthly_prices)
    print(f"Platform: {platform}, Total Cost: ₹{total}")

In [ ]:
subscription_cost("Hotstar", 149, 149, 149)

Platform: Hotstar, Total Cost: ₹447


In [ ]:
subscription_cost("Netflix", 199, 199, 199, 199)

Platform: Netflix, Total Cost: ₹796


In [ ]:
# 2. Example: D-Mart Billing System

In [ ]:
def dmart_bill(customer_name, *item_prices):
    total = sum(item_prices)
    print(f"Customer: {customer_name}, Total Bill: ₹{total}")

In [ ]:
dmart_bill("Amit", 120, 85, 60, 40)

Customer: Amit, Total Bill: ₹305


In [ ]:
dmart_bill("Rohit", 99, 149, 199)

Customer: Rohit, Total Bill: ₹447


# Summary Notes: Positional Arguments and `*args` in Python

In Python, functions can be designed to accept a fixed number of inputs (positional arguments) or a flexible number of inputs using `*args`. Understanding how and when to use these is essential for writing scalable, reusable, and clean code — especially in real-world applications like data processing, configuration handling, and user input collection.

---

## Positional Arguments

Positional arguments are the standard parameters defined in a function. They must be passed in the exact order they are declared. These are ideal when the number of inputs is known and required.

In technical terms, these are called "required positional parameters" because the function signature explicitly expects them. If any are missing or misordered, Python raises a `TypeError`.

---

## `*args` — Variable-Length Positional Arguments

The `*args` syntax allows a function to accept any number of positional arguments. Internally, all values passed to `*args` are collected into a tuple. This makes the function flexible and adaptable to varying input sizes.

In programming terms, `*args` is known as a "variadic positional parameter". It is useful when:
- The number of inputs is not fixed
- You want to allow optional or additional values
- You want to loop over inputs without knowing how many there are

This is commonly used in mathematical operations (like sum, average, product), logging utilities, and APIs where the number of inputs can change.

---

## Mixing Positional Arguments with `*args`

You can combine fixed positional arguments with `*args` in the same function. The fixed arguments must always come first, followed by `*args`. This pattern is often used when you want to ensure certain required inputs (like a user name, label, or identifier) are always provided, while still allowing additional optional values.

This structure is referred to as a "function with leading positional parameters and trailing variadic positional parameters".

---

## Internal Behavior of `*args`

- All values passed to `*args` are stored as a tuple.
- Even if a list is passed as a single argument, it becomes one element inside the tuple.
- You can iterate over `args`, index it, or use built-in functions like `sum()` or `len()` on it.

This behavior is consistent with Python’s design philosophy of treating functions as first-class objects and enabling dynamic input handling.

---

## Best Practices and Rules

- Always place `*args` after all fixed positional arguments.
- Avoid using vague names like `*x` or `*data`; stick to `*args` for clarity and readability.
- Do not place any required positional arguments after `*args` — Python will raise a syntax error.
- Use `*args` only when you genuinely need flexibility; avoid overusing it in simple functions where fixed parameters are clearer.

---

## Real-World Use Cases

- Summing or averaging an unknown number of values
- Logging multiple messages or events
- Accepting multiple user inputs in a single function call
- Building wrappers or decorators that forward arguments to other functions

---

Understanding `*args` is a foundational skill in Python that demonstrates your ability to write adaptable and professional-grade functions. It reflects your grasp of function signatures, argument unpacking, and Python’s dynamic typing system — all of which are frequently discussed in interviews and real-world coding scenarios.


# Day 15: **kwargs & Lambda

## 1. Problem Without `**kwargs`

Suppose you're building a function to store student details:

```python
def student_info(name, age):
    print(f"Name: {name}, Age: {age}")

In [ ]:
def student_info(name, age):
    print(f"Name: {name}, Age: {age}")

student_info(name="Amit", age=21)

Name: Amit, Age: 21


In [ ]:
# But if you try to add more details:
# student_info(name="Amit", age=21, grade="A")

Python throws an error:

**TypeError: student_info() got an unexpected keyword argument 'grade'**


## Solution: Use **kwargs for Flexible Keyword Inputs

To make the function accept any number of named arguments, use **kwarg:

In [ ]:
def student_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

In [ ]:
student_info(name="Amit", age=21, grade="A", city="Pune")

name: Amit
age: 21
grade: A
city: Pune


## Standard Syntax of **kwargs

In [ ]:
def function_name(**kwargs):
    # kwargs is a dictionary
    for key, value in kwargs.items():
        print(key, value)

- **kwargs collects all keyword arguments into a dictionary.

- You can access keys using .keys(), values using .values(), or loop through .items().

## How Data Is Stored Internally

- When you pass keyword arguments, Python stores them as:

In [ ]:
kwargs = {
    "name": "Amit",
    "age": 21,
    "grade": "A"
}

Type: <class 'dict'>

Structure: key–value pairs

## Real-World Example: Online Shopping Cart

In [ ]:
def cart_summary(**items):
    print("Shopping Cart Summary:")
    total = 0
    for product, price in items.items():
        print(f"{product}: ₹{price}")
        total += price
    print(f"Total Amount: ₹{total}")


In [ ]:
cart_summary(Shampoo=120, Rice=250, Milk=60)

Shopping Cart Summary:
Shampoo: ₹120
Rice: ₹250
Milk: ₹60
Total Amount: ₹430


## 6. Summary: Comparison of *args and **kwargs

| Feature        | `*args`                      | `**kwargs`                          |
|----------------|------------------------------|-------------------------------------|
| Input Type     | Positional arguments         | Keyword arguments                   |
| Stored As      | Tuple                        | Dictionary                          |
| Use Case       | Variable-length values       | Variable-length named values        |
| Access Method  | Loop or index                | Loop using `.items()`               |
| Flexibility    | High for numeric or ordered data | High for labeled or optional data |


In [ ]:
# Practice Examples: `**kwargs` in Python

def student_profile(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

In [ ]:
student_profile(name="Amit", age=21, grade="A")

name: Amit
age: 21
grade: A


In [ ]:
# Product Details
def product_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

In [ ]:
product_info(name="Shampoo", brand="Dove", price=120)

name: Shampoo
brand: Dove
price: 120


In [ ]:
# Car Specification
def car_spec(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

In [ ]:
car_spec(model="Fortuner", year=2022, fuel="Diesel")

model: Fortuner
year: 2022
fuel: Diesel


In [ ]:
# Employee Record
def employee_record(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

In [ ]:
employee_record(name="Ravi", department="Sales", salary=45000)

name: Ravi
department: Sales
salary: 45000


In [ ]:
# Online Order Summary
def order_summary(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

In [ ]:
order_summary(item="Laptop", quantity=1, price=55000, delivery="Express")

item: Laptop
quantity: 1
price: 55000
delivery: Express


# Lambda Functions in Python — Overview

## 1. Theoretical Knowledge

A lambda function in Python is a small, anonymous function defined using the `lambda` keyword. Unlike regular functions created with `def`, lambda functions are typically used for short, throwaway operations where defining a full function would be unnecessary. They are often used in functional programming contexts and are limited to a single expression.

Lambda functions are also known as **inline functions** or **anonymous functions** because they don’t require a name unless assigned to a variable.

---

## 2. Syntax

```python
lambda arguments: expression

- arguments: one or more input parameters

- expression: a single operation or return value (no statements or multiple lines)

In [ ]:
lambda x, y: x + y

<function __main__.<lambda>(x, y)>

- This returns a function that adds two numbers.

## 3. Common Use Cases

- Lambda functions are commonly used in:

- Callback functions: when passing logic as an argument

- Quick operations: where defining a full function is unnecessary

- Data transformations: especially in data science workflows

- They are ideal for concise, one-time-use logic embedded directly into function calls or expressions.

# Practice Examples: `**kwargs` in Python

Here are 5 simple and practical examples to help understand how `**kwargs` works.

---

### 1️⃣ Add Two Numbers

In [ ]:
add = lambda x, y: x + y
print(add(10, 5))

15


### 2️⃣ Square of a Number

In [ ]:
square = lambda x: x * x
print(square(6))  # Output: 36

36


### 3️⃣ Check Even or Odd

In [ ]:
is_even = lambda x: x % 2 == 0
print(is_even(7))  # Output: False

False


### 4️⃣ Get Full Name

In [ ]:
full_name = lambda first, last: f"{first} {last}"
print(full_name("Amit", "Patil"))  # Output: Amit Patil

Amit Patil


### 5️⃣ Find Maximum of Two Numbers

In [ ]:
maximum = lambda x, y: x if x > y else y
print(maximum(12, 8))  # Output: 12

12


# Built-in Functions and Modules in Python — Overview

Python provides a rich set of built-in functions and external modules that simplify everyday programming tasks, from basic operations to scientific computing and geolocation.

---

## 1️⃣ Built-in Functions

These are functions available by default in Python — no need to import anything.

| Function   | Purpose                                 | Example                          |
|------------|------------------------------------------|----------------------------------|
| `abs()`    | Returns absolute value                   | `abs(-5)` → `5`                  |
| `print()`  | Displays output                          | `print("Hello")`                 |
| `type()`   | Returns data type                        | `type(10)` → `<class 'int'>`     |
| `len()`    | Returns length of iterable               | `len("Python")` → `6`            |
| `sorted()` | Returns sorted list                      | `sorted([3, 1, 2])` → `[1, 2, 3]` |
| `sum()`    | Returns sum of elements                  | `sum([10, 20])` → `30`           |
| `zip()`    | Combines multiple iterables              | `zip([1,2], ['a','b'])` → pairs  |

These are essential for data manipulation, debugging, and logic building.

---

## 2️⃣ Date and Time Handling

Python’s `datetime` module helps manage dates and times.

```python
from datetime import datetime

now = datetime.now()
formatted = now.strftime("%d-%m-%Y %H:%M:%S")
print(formatted)

.strftime() formats date/time into readable strings.
Useful for timestamps, logs, scheduling, and time-based filtering.


3️⃣ Popular External Modules

Python’s ecosystem includes powerful modules for specialized tasks:

Module	Purpose
---------------
Chempy	Chemistry calculations, periodic table
Geopy	Geolocation and distance calculations
Scipy	Scientific computing, optimization, stats
These modules must be installed via pip and imported before use.

4️⃣ Chempy — Periodic Table Example

python
from chempy import Substance

element = Substance.from_formula("Na")
print(element.name)       # Output: Sodium
print(element.atomic_number)  # Output: 11

Chempy helps visualize and compute chemical properties, ideal for chemistry learners and simulations.

5️⃣ Geopy — Distance Between Two Locations

python
from geopy.distance import distance

loc1 = (18.5204, 73.8567)  # Pune
loc2 = (19.0760, 72.8777)  # Mumbai

print(distance(loc1, loc2).km)  # Output: ~120 km

Geopy is widely used in logistics, mapping apps, and travel planning.

# Day 16 : Introduction to OOP in Python


##  Object-Oriented Programming (OOP) in Python — Day 16 Summary

###  What is OOP?
Object-Oriented Programming (OOP) is a programming paradigm that organizes code using **classes** and **objects** to model real-world entities. It promotes modularity, reusability, and clean structure.

---

###  Where is OOP Used?
- Building scalable software systems
- Game development (e.g., Unity, Pygame)
- GUI applications (e.g., Tkinter, PyQt)
- Web frameworks (e.g., Django, Flask)
- Machine learning pipelines (e.g., scikit-learn models)

---

###  OOP Structure and Key Terms

```python
# Class and Object Example
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def show(self):
        print(f"{self.name} scored {self.marks} marks.")

s1 = Student("Amit", 85)
s1.show()


## 🧩 Breakdown of Class and Object Example in Python

```python
# Class and Object Example
class Student:                                # ➤ Class definition
    def __init__(self, name, marks):          # ➤ Constructor method (__init__)
        self.name = name                      # ➤ Instance variable (attribute)
        self.marks = marks                    # ➤ Instance variable (attribute)

    def show(self):                           # ➤ Instance method
        print(f"{self.name} scored {self.marks} marks.")  # ➤ Method body using attributes

s1 = Student("Amit", 85)                      # ➤ Object instantiation (s1 is an object of Student)
s1.show()                                     # ➤ Method call on the object



## 🧩 OOP Code Breakdown — Tabular Format

| Code Element             | Python Term              | Description                                 |
|--------------------------|--------------------------|---------------------------------------------|
| `class Student:`         | Class Definition         | Blueprint for creating objects              |
| `def __init__`           | Constructor Method       | Initializes object attributes               |
| `self.name, self.marks`  | Instance Variables       | Hold data specific to each object           |
| `def show(self):`        | Instance Method          | Function that operates on object data       |
| `s1 = Student(...)`      | Object Instantiation     | Creates an instance of the class            |
| `s1.show()`              | Method Call              | Calls a method on the object                |



#  Why Use OOP? — Real-Life Comparison

## Scenario: Managing Student Data

---

##  Procedural Approach (No OOP)

### 🔸 Program 1: Add One Student


In [1]:
name1 = "Amit"
marks1 = 85

print(f"{name1} scored {marks1} marks.")

Amit scored 85 marks.


### 🔸 Program 2: Add Another Student

In [2]:
name2 = "Ravi"
marks2 = 90

print(f"{name2} scored {marks2} marks.")

Ravi scored 90 marks.


### 🔸 Program 3: Add Third Student

In [3]:
name3 = "Zoya"
marks3 = 78

print(f"{name3} scored {marks3} marks.")

Zoya scored 78 marks.


#### Problems with Procedural Code:

- Repeating code blocks for each student
- Hard to manage or update data
- No structure for grouping related info
- Not scalable for 100+ students

### OOP Approach — Scalable & Clean

## 🔸 Define a Class

In [4]:
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def show(self):
        print(f"{self.name} scored {self.marks} marks.")


In [6]:
# Create Multiple Students Easily

s1 = Student("Amit", 85)
s2 = Student("Ravi", 90)
s3 = Student("Zoya", 78)

In [7]:
s1.show()
s2.show()
s3.show()

Amit scored 85 marks.
Ravi scored 90 marks.
Zoya scored 78 marks.


Benefits of OOP:

- One class handles all students
- Easy to add, update, or extend features
- Clean structure for large datasets
- Reusable methods and attributes

In [8]:
class Student:
  def __init__(self,name , marks):
    self.name = name
    self.marks = marks

  def show(self):
    print(f"{self.name} scored {self.marks} marks")

In [9]:
student1 = Student("Amit" , 10)

In [13]:
student1.show()

Amit scored 10 marks


# Revisit the OOPs

1. Basic Class and object

Problem: Create a car class with attribtes like brand and model. Then create an instance of this class.

-- attribtes - thease are the like the fancy words, so there is no need to worry too much about this, it's like variables only.

-- Instance: it's like a take a from and fill that from.

2. Class method and self
3. Inheritance.
4. Encapsulation
5. Class Variables
6. Static Method
7. Property Decorators
8. Class inheritance and isinstance() function
9. Multiple Inheritannce


so let's start: like before we had def keyword the same we have the class keyword. as python is object oriented languag so almost most is an object. so object may be come from somthing so it came from class.

make it captalize  name for the class like class Car: so whaterver you write it only in the intendentation of it. now we defiened the class and now we needs to add two attricutes so we will add like brand model. so if we made a class how we can make the object. so if we make the class how we will make it object? so we have the standardize syntax for it. Car(), so we will storein the objext like my_car = Car(). so till we did just

class Car:
    brand = None
    model = None

my_car = Car()
print(my_car)

so we get the object but get the output in the different way. 

so you wanted to add the values so we needs to add the different syntex : like def __init__():

class Car:
    def __init__(userbrand, usermodel):
        brand = userbrand
        model = usermodel

my_car = Car("ToyoTa", "Corolla")
print(my_car.brand)

so the brand is not accessable right now (how the linkage of this variable with the class), so to make the line between class and the parameter so for that we needs to use the self. Like it will make a line between class and the parameter so you can call tehm as we established the line. and if you wanted to access it you needs to you self.userbrand and the self.userbrand


new code will looks like:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = brand

my_car = Car("ToyoTa", "Corolla")

print(my_car.brand)
print(my_car.model)

================================

so suppose you are taking a new car like "TATA". how you will do that.

my_new_car = Car("Tata","Safari") - See you filled the new form, so if you wanted to access any value of this form (class) how you can access it? simply

print(my_new_car.model)
print(my_new_car.brand)

so you made an generalized form and you can use for the multuple entries inside it.so you can save this type of class in the file and when ever you wanted to use import it and use it. 

so what we learnied till now, class Car and the constructure __init__ and the self which called as ....

======================================

let's go for the next question: 

class methos and self : 
problem: Add a method to the car class that displas the full name of the car (brand and model)

- so far inside the class we have added just attributes and add the functioinaly. so it will give the give the full name for the car like first name and the last name. so we will add the functionality like

def full_name(self): # methods setting it up - correct with the correct word
    # reason behind self , it's like we are giving access to .. .. ..
    return f"{self.brand} {self.model}" # so are calling it with our telephone line needs to use the self. (use here the programming defination why we used the self.)

print(my_new_car.full_name())


==================================

let's move for the next question: 
inheritance: 

lets' talk in the normal words the thigns which you get from you parents it can be car or bike or somethings else.

Probelm statememnt: Create and electriccar class thatt inherits from the car class and has an additional attribute battery_size. 

now we wanted to add the attribute not method - attribute - battary_size

class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model
    
    def full_name(self):
        return f"{self.brand} {self.model}"

class ElectricCar(Car): # We are not inheriting, so now we get everything of the Car... correct it with good understanding for students (this comment)
    def __init__(self, brand, model, battery_size):
        super().__init__(brand, model) # it will access from the Car - correct it as per this 
        self.battery_size = battery_size

let's try it now:

my_tesla = ElectricCar("Tesla","Model S", "85KWh)

print(my_tesla.model)

now does the my_tesla have the full_name access? let's see.

print(my_tesla.full_name())


# Python OOP Concepts — Google Colab Notes

Welcome to the Object-Oriented Programming (OOP) journey in Python! Let's break down the key concepts step by step with simple explanations and examples.

---

## 1️⃣ Basic Class and Object

### 🔸 Problem:
Create a `Car` class with attributes like `brand` and `model`. Then create an instance of this class.

### 🔹 What are Attributes?
Attributes are just fancy words for **variables inside a class**. They hold the data related to the object.

### 🔹 What is an Instance?
Think of a class like a blank form. When you fill it out, you create an **instance** — a specific version of that form.

---

###  Example:
```python
class Car:
    brand = None
    model = None

my_car = Car()
print(my_car)
🔸 Output:
This will print something like:

Code
<__main__.Car object at 0x...>
This means you've successfully created an object, but it doesn't show the data yet — because we haven't assigned any values or defined a method to display them.

🧩 Key Notes:
In Python, we use the class keyword to define a class — just like we use def to define a function.

Class names should be capitalized (e.g., Car, Student, BankAccount).

Everything inside the class must be indented properly.

To create an object, use the syntax: my_car = Car()

🔜 Coming Up Next:
Class method and self

Inheritance

Encapsulation

Class Variables

Static Method

Property Decorators

Class inheritance and isinstance() function

Multiple Inheritance

We'll explore each of these with simple examples and analogies to make OOP easy and fun to learn!

# Understanding `__init__()` and `self` in Python Classes

---

## 🔹 Problem:
You want to assign values to a class when creating an object. For that, we use a **constructor method** called `__init__()`.

---

## ❌ Incorrect Code Example
```python
class Car:
    def __init__(userbrand, usermodel):
        brand = userbrand
        model = usermodel

my_car = Car("ToyoTa", "Corolla")
print(my_car.brand)
⚠️ Issue:
brand and model are not linked to the object.

self is missing, so Python doesn’t know these variables belong to the object.

You’ll get an error: 'Car' object has no attribute 'brand'

🔧 Fix: Use self to Link Parameters to the Object

self is like a bridge between the class and the object. It tells Python: “These variables belong to this specific object.”

✅ Correct Code Example
python
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

my_car = Car("ToyoTa", "Corolla")

print(my_car.brand)
print(my_car.model)

🟢 Output:
Code
ToyoTa
Corolla

🧩 Key Notes:
__init__() is the constructor method — it runs automatically when you create an object.

self.brand = brand means: "store the input brand inside the object as self.brand"

You must use self to access or assign object-level data.

This is the foundation of how objects carry their own data in Python!

# 🚗 Creating and Using Objects in Python — Class, `__init__`, and `self`

---

## 🔹 Scenario: You Want to Add a New Car

Let’s say you want to create a new car entry for `"Tata Safari"`.

You already have a class `Car` defined like this:

```python
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model
Now you can create a new car object:

python
my_new_car = Car("Tata", "Safari")

✅ You just filled a form (class) with values — this is called object instantiation.

🔸 Accessing Object Data
To access the values stored in the object:

python
print(my_new_car.brand)   # Output: Tata
print(my_new_car.model)   # Output: Safari

🔹 Why This Is Powerful
* You created a generalized form (class) that can be reused for multiple entries.

* You can create as many car objects as you want with different data.

* You can save this class in a .py file and import it whenever needed.

python
# In another file
from car_module import Car

car1 = Car("Honda", "City")
car2 = Car("Hyundai", "Creta")

🧠 What We’ve Learned So Far
Concept	Meaning

class Car	Defines a blueprint for car objects
__init__	Constructor method that runs when an object is created
self	Connects the object to its attributes and methods
Car(...)	Creates a new object from the class
object.attribute	Accesses data stored in the object


📝 Summary

- A class is like a form template
- An object is like a filled form
- __init__ is the setup function that fills the form
- self is the link between the form and the data

## 🧩 What is an Object in Python?

An **object** is an instance of a class — like a filled-out form based on a template. It holds data (attributes) and can perform actions (methods) defined by the class.

---

### Example:

In [1]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

my_car = Car("Tata", "Safari")

**Here, my_car is an object of the Car class. It stores the brand and model and can access them like this:**

In [2]:
print(my_car.brand)
print(my_car.model) 

Tata
Safari


# 🧠 Class Methods and `self` in Python

---

## 🔹 Problem:
Add a method to the `Car` class that displays the **full name** of the car (brand + model).

So far, we've added attributes to the class. Now we’ll add **functionality** using a method.

---

## 🔸 What is a Method?
A **method** is a function defined inside a class that operates on the object’s data.

---

## 🔸 Why Use `self`?
- `self` is a reference to the **current object**.
- It allows access to the object’s attributes and other methods.
- Think of `self` as a **telephone line** connecting the method to the object’s data.

---

## Example: Adding `full_name()` Method

In [3]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

    def full_name(self):  # Method inside the class
        return f"{self.brand} {self.model}"  # Accessing attributes via self

my_new_car = Car("Tata", "Safari")
print(my_new_car.full_name())

Tata Safari


## 🔑 Key Notes — Understanding Class Methods and `self`

- **`def full_name(self):`** → defines a **method** that belongs to the **class**. It allows the object to perform an action using its own data.

- **`self.brand` and `self.model`** → access the **object's stored data**. These are called **instance attributes**.

- **Why use `self`?**  
  `self` is a reference to the **current object**. Without it, **Python won’t know which object’s data to use** inside the method.

- **💡 Summary:**  
  This is how we add **custom behavior** to our objects — by writing methods that use `self` to interact with the object’s own data.


## Inheritance in Python — Reusing Code from Parent Class

---

##  What is Inheritance?

In simple words, **inheritance** means getting something from your parents — like a car, bike, or house.  
In programming, a **child class** can inherit properties and behaviors from a **parent class**.

---

##  Problem Statement:
Create an `ElectricCar` class that inherits from the `Car` class and adds a new attribute: `battery_size`.

---

##  Step-by-Step Code

In [4]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model
    
    def full_name(self):
        return f"{self.brand} {self.model}"

In [5]:
# Child Class
class ElectricCar(Car):  #  Inheriting from Car class
    def __init__(self, brand, model, battery_size):
        super().__init__(brand, model)  #  Calls the constructor of Car
        self.battery_size = battery_size  #  Adds new attribute specific to ElectricCar

In [6]:
# Let's try it now:
my_tesla = ElectricCar("Tesla", "Model S", "85KWh")

In [7]:
print(my_tesla.model)           # Accessing inherited attribute

Model S


In [8]:
print(my_tesla.full_name())     # Accessing inherited method

Tesla Model S


In [9]:
print(my_tesla.battery_size)    #  Accessing new attribute

85KWh


##  🔑 Key Notes — Understanding Inheritance in Python

---

- **`ElectricCar(Car)`** → This means `ElectricCar` is a **child class** of `Car`.  
  It inherits all the attributes and methods from the parent class.

- **`super().__init__(...)`** → This calls the **constructor of the parent class** (`Car`)  
  and allows us to **reuse its initialization logic**.

-  The child class gets **everything** from the parent:  
  - Attributes (like `brand`, `model`)  
  - Methods (like `full_name()`)

- ➕ You can also **add new attributes or methods** in the child class  
  (e.g., `battery_size` for `ElectricCar`).

-  **Why use inheritance?**  
  It helps you write **cleaner**, **reusable**, and **organized** code —  
  just like getting useful things from your parents without rebuilding them from scratch!


## 🧩 Python OOP Summary Table — Keywords, Meaning, and Use Cases

| 🔑 Keyword / Syntax         | 🧪 Programming Term        | 🖨️ How to Use / Print Out             | 📌 Use Case / Purpose                          |
|----------------------------|----------------------------|---------------------------------------|------------------------------------------------|
| `class Car:`               | Class Definition           | `my_car = Car()`                      | Blueprint for creating objects                |
| `def __init__(...)`        | Constructor Method         | Runs automatically on object creation | Initializes object attributes                 |
| `self`                     | Object Reference           | `self.brand`, `self.model`            | Links object to its own data and methods      |
| `self.brand = brand`       | Attribute Assignment       | `print(my_car.brand)`                 | Stores input data inside the object           |
| `def full_name(self):`     | Instance Method            | `my_car.full_name()`                  | Adds functionality to the object              |
| `super().__init__(...)`    | Parent Constructor Call    | Used inside child class               | Reuses parent class initialization            |
| `ElectricCar(Car)`         | Inheritance Declaration    | `my_tesla = ElectricCar(...)`         | Child class inherits from parent class        |
| `my_car = Car(...)`        | Object Instantiation       | Creates object from class             | Makes usable instance with specific data      |
| `print(my_car.brand)`      | Attribute Access           | Prints stored value                   | Retrieves object data                         |
| `print(my_car.full_name())`| Method Call                | Executes object method                | Displays combined or processed data           |

---

This table summarizes the key OOP components we've used so far, helping you connect syntax with meaning and purpose.


# 🔁 Recap of Yesterday's OOP Topics — Before We Dive into Encapsulation

---

## ✅ What We Covered So Far

We explored the **foundations of Object-Oriented Programming (OOP)** in Python using a simple `Car` class example. Here's a quick summary:

---

### 1️⃣ Class and Object
- Defined a class using `class Car:`
- Created objects like `my_car = Car()`
- Learned that a class is a **blueprint**, and an object is a **filled form**

---

### 2️⃣ Constructor and `self`
- Used `__init__()` to initialize object data
- Connected parameters to object attributes using `self`
- Example:
  ```python
  def __init__(self, brand, model):
      self.brand = brand
      self.model = model

### 3️⃣ Class Method

Added a method full_name() to return the car's full name

Understood that self gives access to the object’s own data

In [1]:
def __init__(self, brand, model):
      self.brand = brand
      self.model = model

### 3️⃣ Class Method

- Added a method full_name() to return the car's full name

- Understood that self gives access to the object’s own data

In [2]:
def full_name(self):
    return f"{self.brand} {self.model}"

### 4️⃣ Inheritance

* Created a child class ElectricCar that inherits from Car

* Used super().__init__() to reuse parent class constructor

* Added a new attribute battery_size

In [5]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model
    
    def full_name(self):
        return f"{self.brand} {self.model}"

In [6]:
# Inheritance
class ElectricCar(Car):
    def __init__(self, brand, model, battery_size):
        super().__init__(brand, model)
        self.battery_size = battery_size

## What We Learned:

- How to define and use classes and objects
- How to initialize data with __init__ and access it using self
- How to add methods for custom behavior
- How to reuse code using inheritance

## 4️⃣ Encapsulation — Protecting and Controlling Access to Data

Problem statement: Modify the Car class to encapsulate the brand attribute, making it private, and provide a getter method for it. 

## 4️⃣ Encapsulation — Protecting and Controlling Access to Data

Problem statement: Modify the Car class to encapsulate the brand attribute, making it private, and provide a getter method for it. 

the concept of encapsulation is that what is inside it depends on my wish if you want to know, i want youto know , if I  don't then you don't. 

so let's the brand attribute should not be in acees to anyone. as it need to make the private. so when you needed the brand what we was doing

print(my_tesla.brand)

so now i don't wanted that should be acess in the future and as per said we wanted to make it private and needs to provide the getter method.

def get_ we will use like

def get_brand(self):
    return self.brand

so now if we try to access it:

print(my_tesla.brand)
print(my_tesla.get_brand())

we still we are able to access it, still the brand is able to access. so here we will do self.__brand

now let's try to access it,
print(my_tesla.brand)
print(my_tesla.__brand)

-- DISPLAY THE OUTPUT HERE as it will be in the markdown. Now it become the private. Private meant that insidethe class you will able to access it but no one if an object created, then that objext will now be will no longer be able to access the object.


and if you want to if people can access it some how we needs to make methods, now see the menthod  we write as get_brand(self).

now explain where this used and why this used with and complate example, so everyeone can understand and able to how can access and which can't be access.

###  Problem Statement:
Modify the `Car` class to **encapsulate** the `brand` attribute, making it **private**, and provide a **getter method** to access it.

####  What is Encapsulation?

Encapsulation means **hiding internal details** of a class and **controlling access** to them.  
In simple words:  
> "If I want you to know something, I’ll give you a way to access it. If I don’t, you can’t touch it."

###  Why Encapsulate?

- To **protect sensitive data**
- To **control how data is accessed or modified**
- To **prevent accidental changes** from outside the class

###  Step-by-Step Example

In [7]:
# Initial Class (No Encapsulation)

class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

my_tesla = Car("Tesla", "Model S")

print(my_tesla.brand)         # Accessible

Tesla


### **Now We Want to Make `brand` Private**

In [8]:
class Car:
    def __init__(self, brand, model):
        self.__brand = brand     # 🔒 Private attribute
        self.model = model

    def get_brand(self):         # ✅ Getter method
        return self.__brand

### Try to Access It

In [9]:
my_tesla = Car("Tesla", "Model S")

In [ ]:
print(my_tesla.get_brand())  # ✅ Accessible

AttributeError: 'Car' object has no attribute 'brand'

In [11]:
print(my_tesla.__brand)      # ❌ Error: 'Car' object has no attribute '__brand'

AttributeError: 'Car' object has no attribute '__brand'

In [12]:
print(my_tesla.get_brand())  # ✅ Output: Tesla

Tesla


## 🔍 Getter Method — Naming and Best Practices

---

### ❓ Do We Need to Write `get_` Before the Attribute Name?

Not strictly — but it's a **widely accepted convention** in Python and other languages.  
Using `get_` makes it clear that the method is meant to **retrieve** a value.

---

###  Example:
```python


In [14]:
class Car:
    def __init__(self, brand):
        self.__brand = brand  # private attribute

    def get_brand(self):     # getter method
        return self.__brand

## 🧠 What to Keep in Mind When Writing Getter Methods

| 🔑 Rule / Tip                  | ✅ Explanation                                                                 |
|-------------------------------|---------------------------------------------------------------------------------|
| **Use `get_` prefix**         | Improves readability and clarity — clearly shows it's a method to retrieve data |
| **Keep method name descriptive** | e.g., `get_brand()` is better than `get_b()` — makes code easier to understand |
| **Only return the private value** | Avoid modifying or exposing internal logic — keep it clean and focused         |
| **Use `self.__attribute` inside it** | Access the private data safely from within the class                          |
| **Avoid direct access from outside** | Always use the getter method to retrieve data — prevents unauthorized access  |

---

### 🧩 Summary

- `get_` is a **naming convention**, not a strict rule — but it helps others understand your code.
- Getter methods are part of **encapsulation**, allowing **controlled access** to private data.

---

### 🔍 Explanation: Avoid Direct Access from Outside

When you declare an attribute as **private** using `__attribute`, it cannot be accessed directly from outside the class:

```python
print(my_car.__brand)  # ❌ Error: Attribute not accessible


In [16]:
my_car = Car("Toyota")

In [20]:
# Instead, you must use a getter method
print(my_car.get_brand())  # ✅ Safe and allowed

# This ensures that the internal data is protected, and only exposed in a controlled and intentional way.

Toyota


## 🧩 Key Notes — Encapsulation in Python

| 🧠 Concept              | 📌 Meaning                                                        |
|------------------------|-------------------------------------------------------------------|
| `__brand`              | Double underscore makes it a **private attribute**                |
| `get_brand()`          | **Getter method** to safely access the private attribute          |
| Direct access blocked  | You **cannot access** `__brand` directly from outside the class   |
| Controlled access      | You **can access** it only through the method provided (`get_brand()`) |

---

###  Where and Why Is This Used?

In **real-world applications**, we often want to **hide internal logic or sensitive data**  
(e.g., passwords, account balance).

**Encapsulation** allows us to **expose only what’s necessary** and **protect the rest**.

It’s a key principle of writing **secure**, **clean**, and **maintainable** code.

In [56]:
class Car:
    def __init__(self,brand , model):
        self.__brand = brand
        self.model = model
    
    def get_brand(self):
        return self.__brand

In [57]:
garage = Car("Tata" , "Safari")

In [58]:
print(garage.model)

Safari


In [59]:
print(garage.get_brand())

Tata


In [62]:

class Car:
    def __init__(self,brand , model):
        self.__brand = brand
        self.model = model
    
    def get_brand(self):
        return self.__brand
    
garage = Car("Tata" , "Safari")
print(garage.get_brand())

Tata


## 5️⃣ Polymorphism — One Interface, Many Behaviors

---

### 🔍 What Is Polymorphism?

**Polymorphism** comes from Greek: *poly* = many, *morph* = forms.  
In real life, think of the word “drive” — you can drive a car, a bike, or a truck.  
Same action, but different behavior depending on the vehicle.

In programming, **polymorphism allows different classes to define methods with the same name but different behavior**.

---

### 🧪 Problem Statement:
Demonstrate polymorphism by defining a method `fuel_type()` in both `Car` and `ElectricCar` classes — each with its own behavior.

---

### Code Example

In [64]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

    def full_name(self):
        return f"{self.brand} {self.model}"
    
    def fuel_type(self):
        return "Petrol or Diseal"

In [65]:
class ElectricCar(Car):
    def __init__(self, brand, model, battery_size):
        super().__init__(brand, model)
        self.battery_size = battery_size

    def fuel_type(self):
        return "Electric Charge"

In [72]:
my_tesla = ElectricCar("Tesla", "Model S", "85KWh")
print(my_tesla.fuel_type())  # Output: Electric Charge

Electric Charge


In [73]:
safari = Car("Tata", "Safari")
print(safari.fuel_type())

Petrol or Diseal


## 🧩 Polymorphism — Method Behavior Across Classes

| 🔑 Concept              | 📌 Explanation                                      |
|------------------------|-----------------------------------------------------|
| `fuel_type()` method   | Defined in both classes with different logic        |
| `my_tesla.fuel_type()` | Calls the version from `ElectricCar`               |
| `safari.fuel_type()`   | Calls the version from `Car`                        |


📌 Why Does Polymorphism Exist?

- To write flexible and reusable code
- To allow different objects to respond differently to the same method call
- To support method overriding in child classes

## 🧩 Where Is It Used Most?

- GUI frameworks: e.g., draw() method for shapes like circle, rectangle, triangle
- Game development: e.g., attack() method for different characters
- Machine learning pipelines: e.g., fit() method for different models
- Web frameworks: e.g., render() method for different page types

### Summary
Polymorphism lets you use one method name across multiple classes, but each class can define its own version of what that method does.

This keeps your code clean, scalable, and easy to extend.